/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adminCleanupMechanics from "../adminCleanupMechanics.js";
import type * as ai_conversations from "../ai_conversations.js";
import type * as ai_enrichment_logs from "../ai_enrichment_logs.js";
import type * as ai_feedback from "../ai_feedback.js";
import type * as ai_messages from "../ai_messages.js";
import type * as analytics_events from "../analytics_events.js";
import type * as app_feedback from "../app_feedback.js";
import type * as audit_log from "../audit_log.js";
import type * as backfillTires from "../backfillTires.js";
import type * as booking_activity from "../booking_activity.js";
import type * as booking_approvals from "../booking_approvals.js";
import type * as booking_disputes from "../booking_disputes.js";
import type * as booking_quotes from "../booking_quotes.js";
import type * as booking_status_history from "../booking_status_history.js";
import type * as bookings from "../bookings.js";
import type * as bugs from "../bugs.js";
import type * as cdn_assets from "../cdn_assets.js";
import type * as chassis_variants from "../chassis_variants.js";
import type * as checkin from "../checkin.js";
import type * as cleanup from "../cleanup.js";
import type * as client_logs from "../client_logs.js";
import type * as conversion_funnels from "../conversion_funnels.js";
import type * as crons from "../crons.js";
import type * as devOnly_validateQuoteEngine from "../devOnly/validateQuoteEngine.js";
import type * as diagnoseVin from "../diagnoseVin.js";
import type * as director from "../director.js";
import type * as directorCars from "../directorCars.js";
import type * as directorConfigActions from "../directorConfigActions.js";
import type * as directorOverview from "../directorOverview.js";
import type * as directorShopActions from "../directorShopActions.js";
import type * as directorStripe from "../directorStripe.js";
import type * as directorStripeLive from "../directorStripeLive.js";
import type * as directorUserActions from "../directorUserActions.js";
import type * as directorVehicleActions from "../directorVehicleActions.js";
import type * as director_auth from "../director_auth.js";
import type * as director_mechanic_verifications from "../director_mechanic_verifications.js";
import type * as director_notes from "../director_notes.js";
import type * as email_dispatcher from "../email_dispatcher.js";
import type * as engines from "../engines.js";
import type * as fitments from "../fitments.js";
import type * as follow_ups from "../follow_ups.js";
import type * as healthPoints from "../healthPoints.js";
import type * as http from "../http.js";
import type * as invitations from "../invitations.js";
import type * as invoices from "../invoices.js";
import type * as invoices_template from "../invoices/template.js";
import type * as invoices_node from "../invoices_node.js";
import type * as jobRecommendations from "../jobRecommendations.js";
import type * as job_actuals from "../job_actuals.js";
import type * as laborTimes from "../laborTimes.js";
import type * as labor_quote_snapshots from "../labor_quote_snapshots.js";
import type * as lib_appleMapsGeocode from "../lib/appleMapsGeocode.js";
import type * as lib_booking_field_redaction from "../lib/booking_field_redaction.js";
import type * as lib_checkin_questions from "../lib/checkin_questions.js";
import type * as lib_classifier from "../lib/classifier.js";
import type * as lib_email_provider from "../lib/email_provider.js";
import type * as lib_haloVariantInference from "../lib/haloVariantInference.js";
import type * as lib_haloVariantRules from "../lib/haloVariantRules.js";
import type * as lib_intervals from "../lib/intervals.js";
import type * as lib_job_actuals from "../lib/job_actuals.js";
import type * as lib_late_start from "../lib/late_start.js";
import type * as lib_modifiers from "../lib/modifiers.js";
import type * as lib_notificationScope from "../lib/notificationScope.js";
import type * as lib_packageRules from "../lib/packageRules.js";
import type * as lib_payment_constants from "../lib/payment_constants.js";
import type * as lib_push_dispatcher from "../lib/push_dispatcher.js";
import type * as lib_quoteEngine from "../lib/quoteEngine.js";
import type * as lib_schedule_overlap from "../lib/schedule_overlap.js";
import type * as lib_serviceWindow from "../lib/serviceWindow.js";
import type * as lib_simpleTireScraper from "../lib/simpleTireScraper.js";
import type * as lib_sms_provider from "../lib/sms_provider.js";
import type * as lib_stripeTax from "../lib/stripeTax.js";
import type * as lib_stripe_void from "../lib/stripe_void.js";
import type * as lib_telnyx_webhook from "../lib/telnyx_webhook.js";
import type * as lib_timeSlotAvailability from "../lib/timeSlotAvailability.js";
import type * as lib_tireBrands from "../lib/tireBrands.js";
import type * as lib_tireRackScraper from "../lib/tireRackScraper.js";
import type * as lib_transmissionTypeInference from "../lib/transmissionTypeInference.js";
import type * as lib_vdbCache from "../lib/vdbCache.js";
import type * as lib_vehicleDatabases from "../lib/vehicleDatabases.js";
import type * as lib_vehicleTiers from "../lib/vehicleTiers.js";
import type * as lib_vehicle_image from "../lib/vehicle_image.js";
import type * as lib_vehicle_passports from "../lib/vehicle_passports.js";
import type * as lib_walmartTireScraper from "../lib/walmartTireScraper.js";
import type * as maintenance from "../maintenance.js";
import type * as maintenance_pipeline from "../maintenance_pipeline.js";
import type * as makes from "../makes.js";
import type * as manual_review_queue from "../manual_review_queue.js";
import type * as mcp_api from "../mcp_api.js";
import type * as mechanicNotifications from "../mechanicNotifications.js";
import type * as mechanics from "../mechanics.js";
import type * as migrations from "../migrations.js";
import type * as models from "../models.js";
import type * as notifications from "../notifications.js";
import type * as oemParts from "../oemParts.js";
import type * as onboarding_questions_answers from "../onboarding_questions_answers.js";
import type * as oto_bookings from "../oto/bookings.js";
import type * as oto_canonicalize from "../oto/canonicalize.js";
import type * as oto_chat from "../oto/chat.js";
import type * as oto_dispatcher from "../oto/dispatcher.js";
import type * as oto_dueServices from "../oto/dueServices.js";
import type * as oto_envelope from "../oto/envelope.js";
import type * as oto_evalHarness from "../oto/evalHarness.js";
import type * as oto_evalTestFilter from "../oto/evalTestFilter.js";
import type * as oto_factReports from "../oto/factReports.js";
import type * as oto_lookupVehicleSpec from "../oto/lookupVehicleSpec.js";
import type * as oto_memoryDecay from "../oto/memoryDecay.js";
import type * as oto_memoryEditing from "../oto/memoryEditing.js";
import type * as oto_memoryEquivalence from "../oto/memoryEquivalence.js";
import type * as oto_migrations_backfillV3Lifecycle from "../oto/migrations/backfillV3Lifecycle.js";
import type * as oto_migrations_evalTenantsSeed from "../oto/migrations/evalTenantsSeed.js";
import type * as oto_migrations_vehicleFactsReconciliation from "../oto/migrations/vehicleFactsReconciliation.js";
import type * as oto_migrations_verifiedFactsSeed from "../oto/migrations/verifiedFactsSeed.js";
import type * as oto_migrations_wave3Backfill from "../oto/migrations/wave3Backfill.js";
import type * as oto_promptChangelog from "../oto/promptChangelog.js";
import type * as oto_prompt_index from "../oto/prompt/index.js";
import type * as oto_prompt_stable from "../oto/prompt/stable.js";
import type * as oto_prompt_volatile from "../oto/prompt/volatile.js";
import type * as oto_queryMoat from "../oto/queryMoat.js";
import type * as oto_recordConfirmation from "../oto/recordConfirmation.js";
import type * as oto_reliability from "../oto/reliability.js";
import type * as oto_searchedFacts from "../oto/searchedFacts.js";
import type * as oto_system_prompt from "../oto/system_prompt.js";
import type * as oto_telemetry from "../oto/telemetry.js";
import type * as oto_tools from "../oto/tools.js";
import type * as oto_vehicleFacts from "../oto/vehicleFacts.js";
import type * as oto_vehicleFactsEditing from "../oto/vehicleFactsEditing.js";
import type * as oto_vehicleFactsKB from "../oto/vehicleFactsKB.js";
import type * as oto_vehicleHealth from "../oto/vehicleHealth.js";
import type * as partSelector from "../partSelector.js";
import type * as part_prices from "../part_prices.js";
import type * as part_snapshots from "../part_snapshots.js";
import type * as payment_disputes from "../payment_disputes.js";
import type * as payment_status_history from "../payment_status_history.js";
import type * as payments from "../payments.js";
import type * as payments_backfill from "../payments_backfill.js";
import type * as payments_backfill_helpers from "../payments_backfill_helpers.js";
import type * as payments_stripe from "../payments_stripe.js";
import type * as platform_settings from "../platform_settings.js";
import type * as preferences from "../preferences.js";
import type * as pricing from "../pricing.js";
import type * as quote_request_dismissals from "../quote_request_dismissals.js";
import type * as quotes from "../quotes.js";
import type * as referrals from "../referrals.js";
import type * as retrigger_enrichment from "../retrigger_enrichment.js";
import type * as reviews from "../reviews.js";
import type * as rewards from "../rewards.js";
import type * as rotor_quote_responses from "../rotor_quote_responses.js";
import type * as schedule from "../schedule.js";
import type * as seed from "../seed.js";
import type * as seed_modifier_weights from "../seed_modifier_weights.js";
import type * as seed_services from "../seed_services.js";
import type * as seed_services_catalog from "../seed_services_catalog.js";
import type * as seed_transactions from "../seed_transactions.js";
import type * as seeds_blockEbay from "../seeds/blockEbay.js";
import type * as seeds_cleanAndRerun from "../seeds/cleanAndRerun.js";
import type * as seeds_deleteAndRerunNissan from "../seeds/deleteAndRerunNissan.js";
import type * as seeds_deleteByVin from "../seeds/deleteByVin.js";
import type * as seeds_evidenceReport from "../seeds/evidenceReport.js";
import type * as seeds_fullCleanAndRerun from "../seeds/fullCleanAndRerun.js";
import type * as seeds_seedBlockedDomains from "../seeds/seedBlockedDomains.js";
import type * as seeds_seedCamryBaseline from "../seeds/seedCamryBaseline.js";
import type * as seeds_seedMakes from "../seeds/seedMakes.js";
import type * as seeds_seedPricing from "../seeds/seedPricing.js";
import type * as seeds_seedPricingV2 from "../seeds/seedPricingV2.js";
import type * as seeds_seedServiceCategories from "../seeds/seedServiceCategories.js";
import type * as seeds_seedServices from "../seeds/seedServices.js";
import type * as seeds_seedShopLaborRates from "../seeds/seedShopLaborRates.js";
import type * as seeds_seedTierAssignments from "../seeds/seedTierAssignments.js";
import type * as seeds_testEnrichment from "../seeds/testEnrichment.js";
import type * as serviceParts from "../serviceParts.js";
import type * as service_categories from "../service_categories.js";
import type * as service_insights from "../service_insights.js";
import type * as service_options from "../service_options.js";
import type * as service_vehicle_specs from "../service_vehicle_specs.js";
import type * as services from "../services.js";
import type * as services_applicability from "../services/applicability.js";
import type * as services_consensus from "../services/consensus.js";
import type * as services_constants from "../services/constants.js";
import type * as services_normalization from "../services/normalization.js";
import type * as services_sourceScoring from "../services/sourceScoring.js";
import type * as services_verification from "../services/verification.js";
import type * as shopCustomers from "../shopCustomers.js";
import type * as shopLaborRates from "../shopLaborRates.js";
import type * as shopServiceFixedPrices from "../shopServiceFixedPrices.js";
import type * as shop_part_preferences from "../shop_part_preferences.js";
import type * as shop_portfolio from "../shop_portfolio.js";
import type * as shop_services from "../shop_services.js";
import type * as shops from "../shops.js";
import type * as shops_hours from "../shops_hours.js";
import type * as smartcar from "../smartcar.js";
import type * as sms_dispatcher from "../sms_dispatcher.js";
import type * as spec_confirmations from "../spec_confirmations.js";
import type * as spec_variances from "../spec_variances.js";
import type * as specs from "../specs.js";
import type * as stripe_webhook_events from "../stripe_webhook_events.js";
import type * as telnyx from "../telnyx.js";
import type * as test_helpers from "../test_helpers.js";
import type * as time_slots from "../time_slots.js";
import type * as tireBrands from "../tireBrands.js";
import type * as tire_quote_responses from "../tire_quote_responses.js";
import type * as tires from "../tires.js";
import type * as tires_catalog from "../tires_catalog.js";
import type * as transactions from "../transactions.js";
import type * as transmissions from "../transmissions.js";
import type * as trims from "../trims.js";
import type * as undoMechanicVerification from "../undoMechanicVerification.js";
import type * as userAddresses from "../userAddresses.js";
import type * as users from "../users.js";
import type * as vehicleEnrichment_adversarialVerification from "../vehicleEnrichment/adversarialVerification.js";
import type * as vehicleEnrichment_anomalyDetection from "../vehicleEnrichment/anomalyDetection.js";
import type * as vehicleEnrichment_applicabilityRules from "../vehicleEnrichment/applicabilityRules.js";
import type * as vehicleEnrichment_backfillNhtsaKey from "../vehicleEnrichment/backfillNhtsaKey.js";
import type * as vehicleEnrichment_blockedDomains from "../vehicleEnrichment/blockedDomains.js";
import type * as vehicleEnrichment_buildSearchQueries from "../vehicleEnrichment/buildSearchQueries.js";
import type * as vehicleEnrichment_cacheValidation from "../vehicleEnrichment/cacheValidation.js";
import type * as vehicleEnrichment_claudeExtractor from "../vehicleEnrichment/claudeExtractor.js";
import type * as vehicleEnrichment_contentSanitization from "../vehicleEnrichment/contentSanitization.js";
import type * as vehicleEnrichment_evidenceConsensus from "../vehicleEnrichment/evidenceConsensus.js";
import type * as vehicleEnrichment_extractionPrompts from "../vehicleEnrichment/extractionPrompts.js";
import type * as vehicleEnrichment_firecrawl from "../vehicleEnrichment/firecrawl.js";
import type * as vehicleEnrichment_gapFill from "../vehicleEnrichment/gapFill.js";
import type * as vehicleEnrichment_helpers from "../vehicleEnrichment/helpers.js";
import type * as vehicleEnrichment_marketplaceScraper from "../vehicleEnrichment/marketplaceScraper.js";
import type * as vehicleEnrichment_mutations from "../vehicleEnrichment/mutations.js";
import type * as vehicleEnrichment_nhtsa from "../vehicleEnrichment/nhtsa.js";
import type * as vehicleEnrichment_partialEnrichment from "../vehicleEnrichment/partialEnrichment.js";
import type * as vehicleEnrichment_pipelineBatch from "../vehicleEnrichment/pipelineBatch.js";
import type * as vehicleEnrichment_pipelineTest from "../vehicleEnrichment/pipelineTest.js";
import type * as vehicleEnrichment_prompts_batch1Prompt from "../vehicleEnrichment/prompts/batch1Prompt.js";
import type * as vehicleEnrichment_prompts_batch1bPrompt from "../vehicleEnrichment/prompts/batch1bPrompt.js";
import type * as vehicleEnrichment_prompts_batch2Prompt from "../vehicleEnrichment/prompts/batch2Prompt.js";
import type * as vehicleEnrichment_queries from "../vehicleEnrichment/queries.js";
import type * as vehicleEnrichment_runHeadless from "../vehicleEnrichment/runHeadless.js";
import type * as vehicleEnrichment_runPublic from "../vehicleEnrichment/runPublic.js";
import type * as vehicleEnrichment_runTest from "../vehicleEnrichment/runTest.js";
import type * as vehicleEnrichment_scraper from "../vehicleEnrichment/scraper.js";
import type * as vehicleEnrichment_scraperQueries from "../vehicleEnrichment/scraperQueries.js";
import type * as vehicleEnrichment_searchPreGather from "../vehicleEnrichment/searchPreGather.js";
import type * as vehicleEnrichment_sourceDiscovery from "../vehicleEnrichment/sourceDiscovery.js";
import type * as vehicleEnrichment_sourceRegistry from "../vehicleEnrichment/sourceRegistry.js";
import type * as vehicleEnrichment_sourceVerifier from "../vehicleEnrichment/sourceVerifier.js";
import type * as vehicleEnrichment_tier2Enrichment from "../vehicleEnrichment/tier2Enrichment.js";
import type * as vehicleEnrichment_types from "../vehicleEnrichment/types.js";
import type * as vehicleEnrichment_utils_batchClient from "../vehicleEnrichment/utils/batchClient.js";
import type * as vehicleEnrichment_utils_chassisLookup from "../vehicleEnrichment/utils/chassisLookup.js";
import type * as vehicleEnrichment_utils_claudeClient from "../vehicleEnrichment/utils/claudeClient.js";
import type * as vehicleEnrichment_utils_engineCodeLookup from "../vehicleEnrichment/utils/engineCodeLookup.js";
import type * as vehicleEnrichment_utils_engineLookup from "../vehicleEnrichment/utils/engineLookup.js";
import type * as vehicleEnrichment_utils_wheelSizeScraper from "../vehicleEnrichment/utils/wheelSizeScraper.js";
import type * as vehicleEnrichment_v3TestSuite from "../vehicleEnrichment/v3TestSuite.js";
import type * as vehicleEnrichment_v3mutations from "../vehicleEnrichment/v3mutations.js";
import type * as vehicleEnrichment_v3pipeline from "../vehicleEnrichment/v3pipeline.js";
import type * as vehicleEnrichment_v3queries from "../vehicleEnrichment/v3queries.js";
import type * as vehicleEnrichment_validation_oemValidation from "../vehicleEnrichment/validation/oemValidation.js";
import type * as vehicleEnrichment_validation_sanityChecks from "../vehicleEnrichment/validation/sanityChecks.js";
import type * as vehicleEnrichment_verificationApi from "../vehicleEnrichment/verificationApi.js";
import type * as vehicle_mutations from "../vehicle_mutations.js";
import type * as vehicle_owners from "../vehicle_owners.js";
import type * as vehicle_pipeline from "../vehicle_pipeline.js";
import type * as vehicle_specs from "../vehicle_specs.js";
import type * as vehicles from "../vehicles.js";
import type * as walkin_claims from "../walkin_claims.js";
import type * as ymmtCatalog from "../ymmtCatalog.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  adminCleanupMechanics: typeof adminCleanupMechanics;
  ai_conversations: typeof ai_conversations;
  ai_enrichment_logs: typeof ai_enrichment_logs;
  ai_feedback: typeof ai_feedback;
  ai_messages: typeof ai_messages;
  analytics_events: typeof analytics_events;
  app_feedback: typeof app_feedback;
  audit_log: typeof audit_log;
  backfillTires: typeof backfillTires;
  booking_activity: typeof booking_activity;
  booking_approvals: typeof booking_approvals;
  booking_disputes: typeof booking_disputes;
  booking_quotes: typeof booking_quotes;
  booking_status_history: typeof booking_status_history;
  bookings: typeof bookings;
  bugs: typeof bugs;
  cdn_assets: typeof cdn_assets;
  chassis_variants: typeof chassis_variants;
  checkin: typeof checkin;
  cleanup: typeof cleanup;
  client_logs: typeof client_logs;
  conversion_funnels: typeof conversion_funnels;
  crons: typeof crons;
  "devOnly/validateQuoteEngine": typeof devOnly_validateQuoteEngine;
  diagnoseVin: typeof diagnoseVin;
  director: typeof director;
  directorCars: typeof directorCars;
  directorConfigActions: typeof directorConfigActions;
  directorOverview: typeof directorOverview;
  directorShopActions: typeof directorShopActions;
  directorStripe: typeof directorStripe;
  directorStripeLive: typeof directorStripeLive;
  directorUserActions: typeof directorUserActions;
  directorVehicleActions: typeof directorVehicleActions;
  director_auth: typeof director_auth;
  director_mechanic_verifications: typeof director_mechanic_verifications;
  director_notes: typeof director_notes;
  email_dispatcher: typeof email_dispatcher;
  engines: typeof engines;
  fitments: typeof fitments;
  follow_ups: typeof follow_ups;
  healthPoints: typeof healthPoints;
  http: typeof http;
  invitations: typeof invitations;
  invoices: typeof invoices;
  "invoices/template": typeof invoices_template;
  invoices_node: typeof invoices_node;
  jobRecommendations: typeof jobRecommendations;
  job_actuals: typeof job_actuals;
  laborTimes: typeof laborTimes;
  labor_quote_snapshots: typeof labor_quote_snapshots;
  "lib/appleMapsGeocode": typeof lib_appleMapsGeocode;
  "lib/booking_field_redaction": typeof lib_booking_field_redaction;
  "lib/checkin_questions": typeof lib_checkin_questions;
  "lib/classifier": typeof lib_classifier;
  "lib/email_provider": typeof lib_email_provider;
  "lib/haloVariantInference": typeof lib_haloVariantInference;
  "lib/haloVariantRules": typeof lib_haloVariantRules;
  "lib/intervals": typeof lib_intervals;
  "lib/job_actuals": typeof lib_job_actuals;
  "lib/late_start": typeof lib_late_start;
  "lib/modifiers": typeof lib_modifiers;
  "lib/notificationScope": typeof lib_notificationScope;
  "lib/packageRules": typeof lib_packageRules;
  "lib/payment_constants": typeof lib_payment_constants;
  "lib/push_dispatcher": typeof lib_push_dispatcher;
  "lib/quoteEngine": typeof lib_quoteEngine;
  "lib/schedule_overlap": typeof lib_schedule_overlap;
  "lib/serviceWindow": typeof lib_serviceWindow;
  "lib/simpleTireScraper": typeof lib_simpleTireScraper;
  "lib/sms_provider": typeof lib_sms_provider;
  "lib/stripeTax": typeof lib_stripeTax;
  "lib/stripe_void": typeof lib_stripe_void;
  "lib/telnyx_webhook": typeof lib_telnyx_webhook;
  "lib/timeSlotAvailability": typeof lib_timeSlotAvailability;
  "lib/tireBrands": typeof lib_tireBrands;
  "lib/tireRackScraper": typeof lib_tireRackScraper;
  "lib/transmissionTypeInference": typeof lib_transmissionTypeInference;
  "lib/vdbCache": typeof lib_vdbCache;
  "lib/vehicleDatabases": typeof lib_vehicleDatabases;
  "lib/vehicleTiers": typeof lib_vehicleTiers;
  "lib/vehicle_image": typeof lib_vehicle_image;
  "lib/vehicle_passports": typeof lib_vehicle_passports;
  "lib/walmartTireScraper": typeof lib_walmartTireScraper;
  maintenance: typeof maintenance;
  maintenance_pipeline: typeof maintenance_pipeline;
  makes: typeof makes;
  manual_review_queue: typeof manual_review_queue;
  mcp_api: typeof mcp_api;
  mechanicNotifications: typeof mechanicNotifications;
  mechanics: typeof mechanics;
  migrations: typeof migrations;
  models: typeof models;
  notifications: typeof notifications;
  oemParts: typeof oemParts;
  onboarding_questions_answers: typeof onboarding_questions_answers;
  "oto/bookings": typeof oto_bookings;
  "oto/canonicalize": typeof oto_canonicalize;
  "oto/chat": typeof oto_chat;
  "oto/dispatcher": typeof oto_dispatcher;
  "oto/dueServices": typeof oto_dueServices;
  "oto/envelope": typeof oto_envelope;
  "oto/evalHarness": typeof oto_evalHarness;
  "oto/evalTestFilter": typeof oto_evalTestFilter;
  "oto/factReports": typeof oto_factReports;
  "oto/lookupVehicleSpec": typeof oto_lookupVehicleSpec;
  "oto/memoryDecay": typeof oto_memoryDecay;
  "oto/memoryEditing": typeof oto_memoryEditing;
  "oto/memoryEquivalence": typeof oto_memoryEquivalence;
  "oto/migrations/backfillV3Lifecycle": typeof oto_migrations_backfillV3Lifecycle;
  "oto/migrations/evalTenantsSeed": typeof oto_migrations_evalTenantsSeed;
  "oto/migrations/vehicleFactsReconciliation": typeof oto_migrations_vehicleFactsReconciliation;
  "oto/migrations/verifiedFactsSeed": typeof oto_migrations_verifiedFactsSeed;
  "oto/migrations/wave3Backfill": typeof oto_migrations_wave3Backfill;
  "oto/promptChangelog": typeof oto_promptChangelog;
  "oto/prompt/index": typeof oto_prompt_index;
  "oto/prompt/stable": typeof oto_prompt_stable;
  "oto/prompt/volatile": typeof oto_prompt_volatile;
  "oto/queryMoat": typeof oto_queryMoat;
  "oto/recordConfirmation": typeof oto_recordConfirmation;
  "oto/reliability": typeof oto_reliability;
  "oto/searchedFacts": typeof oto_searchedFacts;
  "oto/system_prompt": typeof oto_system_prompt;
  "oto/telemetry": typeof oto_telemetry;
  "oto/tools": typeof oto_tools;
  "oto/vehicleFacts": typeof oto_vehicleFacts;
  "oto/vehicleFactsEditing": typeof oto_vehicleFactsEditing;
  "oto/vehicleFactsKB": typeof oto_vehicleFactsKB;
  "oto/vehicleHealth": typeof oto_vehicleHealth;
  partSelector: typeof partSelector;
  part_prices: typeof part_prices;
  part_snapshots: typeof part_snapshots;
  payment_disputes: typeof payment_disputes;
  payment_status_history: typeof payment_status_history;
  payments: typeof payments;
  payments_backfill: typeof payments_backfill;
  payments_backfill_helpers: typeof payments_backfill_helpers;
  payments_stripe: typeof payments_stripe;
  platform_settings: typeof platform_settings;
  preferences: typeof preferences;
  pricing: typeof pricing;
  quote_request_dismissals: typeof quote_request_dismissals;
  quotes: typeof quotes;
  referrals: typeof referrals;
  retrigger_enrichment: typeof retrigger_enrichment;
  reviews: typeof reviews;
  rewards: typeof rewards;
  rotor_quote_responses: typeof rotor_quote_responses;
  schedule: typeof schedule;
  seed: typeof seed;
  seed_modifier_weights: typeof seed_modifier_weights;
  seed_services: typeof seed_services;
  seed_services_catalog: typeof seed_services_catalog;
  seed_transactions: typeof seed_transactions;
  "seeds/blockEbay": typeof seeds_blockEbay;
  "seeds/cleanAndRerun": typeof seeds_cleanAndRerun;
  "seeds/deleteAndRerunNissan": typeof seeds_deleteAndRerunNissan;
  "seeds/deleteByVin": typeof seeds_deleteByVin;
  "seeds/evidenceReport": typeof seeds_evidenceReport;
  "seeds/fullCleanAndRerun": typeof seeds_fullCleanAndRerun;
  "seeds/seedBlockedDomains": typeof seeds_seedBlockedDomains;
  "seeds/seedCamryBaseline": typeof seeds_seedCamryBaseline;
  "seeds/seedMakes": typeof seeds_seedMakes;
  "seeds/seedPricing": typeof seeds_seedPricing;
  "seeds/seedPricingV2": typeof seeds_seedPricingV2;
  "seeds/seedServiceCategories": typeof seeds_seedServiceCategories;
  "seeds/seedServices": typeof seeds_seedServices;
  "seeds/seedShopLaborRates": typeof seeds_seedShopLaborRates;
  "seeds/seedTierAssignments": typeof seeds_seedTierAssignments;
  "seeds/testEnrichment": typeof seeds_testEnrichment;
  serviceParts: typeof serviceParts;
  service_categories: typeof service_categories;
  service_insights: typeof service_insights;
  service_options: typeof service_options;
  service_vehicle_specs: typeof service_vehicle_specs;
  services: typeof services;
  "services/applicability": typeof services_applicability;
  "services/consensus": typeof services_consensus;
  "services/constants": typeof services_constants;
  "services/normalization": typeof services_normalization;
  "services/sourceScoring": typeof services_sourceScoring;
  "services/verification": typeof services_verification;
  shopCustomers: typeof shopCustomers;
  shopLaborRates: typeof shopLaborRates;
  shopServiceFixedPrices: typeof shopServiceFixedPrices;
  shop_part_preferences: typeof shop_part_preferences;
  shop_portfolio: typeof shop_portfolio;
  shop_services: typeof shop_services;
  shops: typeof shops;
  shops_hours: typeof shops_hours;
  smartcar: typeof smartcar;
  sms_dispatcher: typeof sms_dispatcher;
  spec_confirmations: typeof spec_confirmations;
  spec_variances: typeof spec_variances;
  specs: typeof specs;
  stripe_webhook_events: typeof stripe_webhook_events;
  telnyx: typeof telnyx;
  test_helpers: typeof test_helpers;
  time_slots: typeof time_slots;
  tireBrands: typeof tireBrands;
  tire_quote_responses: typeof tire_quote_responses;
  tires: typeof tires;
  tires_catalog: typeof tires_catalog;
  transactions: typeof transactions;
  transmissions: typeof transmissions;
  trims: typeof trims;
  undoMechanicVerification: typeof undoMechanicVerification;
  userAddresses: typeof userAddresses;
  users: typeof users;
  "vehicleEnrichment/adversarialVerification": typeof vehicleEnrichment_adversarialVerification;
  "vehicleEnrichment/anomalyDetection": typeof vehicleEnrichment_anomalyDetection;
  "vehicleEnrichment/applicabilityRules": typeof vehicleEnrichment_applicabilityRules;
  "vehicleEnrichment/backfillNhtsaKey": typeof vehicleEnrichment_backfillNhtsaKey;
  "vehicleEnrichment/blockedDomains": typeof vehicleEnrichment_blockedDomains;
  "vehicleEnrichment/buildSearchQueries": typeof vehicleEnrichment_buildSearchQueries;
  "vehicleEnrichment/cacheValidation": typeof vehicleEnrichment_cacheValidation;
  "vehicleEnrichment/claudeExtractor": typeof vehicleEnrichment_claudeExtractor;
  "vehicleEnrichment/contentSanitization": typeof vehicleEnrichment_contentSanitization;
  "vehicleEnrichment/evidenceConsensus": typeof vehicleEnrichment_evidenceConsensus;
  "vehicleEnrichment/extractionPrompts": typeof vehicleEnrichment_extractionPrompts;
  "vehicleEnrichment/firecrawl": typeof vehicleEnrichment_firecrawl;
  "vehicleEnrichment/gapFill": typeof vehicleEnrichment_gapFill;
  "vehicleEnrichment/helpers": typeof vehicleEnrichment_helpers;
  "vehicleEnrichment/marketplaceScraper": typeof vehicleEnrichment_marketplaceScraper;
  "vehicleEnrichment/mutations": typeof vehicleEnrichment_mutations;
  "vehicleEnrichment/nhtsa": typeof vehicleEnrichment_nhtsa;
  "vehicleEnrichment/partialEnrichment": typeof vehicleEnrichment_partialEnrichment;
  "vehicleEnrichment/pipelineBatch": typeof vehicleEnrichment_pipelineBatch;
  "vehicleEnrichment/pipelineTest": typeof vehicleEnrichment_pipelineTest;
  "vehicleEnrichment/prompts/batch1Prompt": typeof vehicleEnrichment_prompts_batch1Prompt;
  "vehicleEnrichment/prompts/batch1bPrompt": typeof vehicleEnrichment_prompts_batch1bPrompt;
  "vehicleEnrichment/prompts/batch2Prompt": typeof vehicleEnrichment_prompts_batch2Prompt;
  "vehicleEnrichment/queries": typeof vehicleEnrichment_queries;
  "vehicleEnrichment/runHeadless": typeof vehicleEnrichment_runHeadless;
  "vehicleEnrichment/runPublic": typeof vehicleEnrichment_runPublic;
  "vehicleEnrichment/runTest": typeof vehicleEnrichment_runTest;
  "vehicleEnrichment/scraper": typeof vehicleEnrichment_scraper;
  "vehicleEnrichment/scraperQueries": typeof vehicleEnrichment_scraperQueries;
  "vehicleEnrichment/searchPreGather": typeof vehicleEnrichment_searchPreGather;
  "vehicleEnrichment/sourceDiscovery": typeof vehicleEnrichment_sourceDiscovery;
  "vehicleEnrichment/sourceRegistry": typeof vehicleEnrichment_sourceRegistry;
  "vehicleEnrichment/sourceVerifier": typeof vehicleEnrichment_sourceVerifier;
  "vehicleEnrichment/tier2Enrichment": typeof vehicleEnrichment_tier2Enrichment;
  "vehicleEnrichment/types": typeof vehicleEnrichment_types;
  "vehicleEnrichment/utils/batchClient": typeof vehicleEnrichment_utils_batchClient;
  "vehicleEnrichment/utils/chassisLookup": typeof vehicleEnrichment_utils_chassisLookup;
  "vehicleEnrichment/utils/claudeClient": typeof vehicleEnrichment_utils_claudeClient;
  "vehicleEnrichment/utils/engineCodeLookup": typeof vehicleEnrichment_utils_engineCodeLookup;
  "vehicleEnrichment/utils/engineLookup": typeof vehicleEnrichment_utils_engineLookup;
  "vehicleEnrichment/utils/wheelSizeScraper": typeof vehicleEnrichment_utils_wheelSizeScraper;
  "vehicleEnrichment/v3TestSuite": typeof vehicleEnrichment_v3TestSuite;
  "vehicleEnrichment/v3mutations": typeof vehicleEnrichment_v3mutations;
  "vehicleEnrichment/v3pipeline": typeof vehicleEnrichment_v3pipeline;
  "vehicleEnrichment/v3queries": typeof vehicleEnrichment_v3queries;
  "vehicleEnrichment/validation/oemValidation": typeof vehicleEnrichment_validation_oemValidation;
  "vehicleEnrichment/validation/sanityChecks": typeof vehicleEnrichment_validation_sanityChecks;
  "vehicleEnrichment/verificationApi": typeof vehicleEnrichment_verificationApi;
  vehicle_mutations: typeof vehicle_mutations;
  vehicle_owners: typeof vehicle_owners;
  vehicle_pipeline: typeof vehicle_pipeline;
  vehicle_specs: typeof vehicle_specs;
  vehicles: typeof vehicles;
  walkin_claims: typeof walkin_claims;
  ymmtCatalog: typeof ymmtCatalog;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
