/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _diagnostic_i1_i2 from "../_diagnostic_i1_i2.js";
import type * as _seedDemo from "../_seedDemo.js";
import type * as adminCleanupMechanics from "../adminCleanupMechanics.js";
import type * as ai_conversations from "../ai_conversations.js";
import type * as ai_enrichment_logs from "../ai_enrichment_logs.js";
import type * as ai_feedback from "../ai_feedback.js";
import type * as ai_messages from "../ai_messages.js";
import type * as analytics_events from "../analytics_events.js";
import type * as app_feedback from "../app_feedback.js";
import type * as audit_log from "../audit_log.js";
import type * as backfillTires from "../backfillTires.js";
import type * as backfillVdbBrakes from "../backfillVdbBrakes.js";
import type * as booking_activity from "../booking_activity.js";
import type * as booking_approvals from "../booking_approvals.js";
import type * as booking_disputes from "../booking_disputes.js";
import type * as booking_quotes from "../booking_quotes.js";
import type * as booking_status_history from "../booking_status_history.js";
import type * as bookings from "../bookings.js";
import type * as bugs from "../bugs.js";
import type * as cdn_assets from "../cdn_assets.js";
import type * as chassis_variants from "../chassis_variants.js";
import type * as checkin from "../checkin.js";
import type * as cleanup from "../cleanup.js";
import type * as client_logs from "../client_logs.js";
import type * as configsMerge from "../configsMerge.js";
import type * as conversion_funnels from "../conversion_funnels.js";
import type * as crons from "../crons.js";
import type * as customJobs from "../customJobs.js";
import type * as dataApi from "../dataApi.js";
import type * as dataApiEnrich from "../dataApiEnrich.js";
import type * as dataCatalog from "../dataCatalog.js";
import type * as dataControlRoom from "../dataControlRoom.js";
import type * as dataCosts from "../dataCosts.js";
import type * as dataCoverage from "../dataCoverage.js";
import type * as dataInsights from "../dataInsights.js";
import type * as dataLabor from "../dataLabor.js";
import type * as dataOverview from "../dataOverview.js";
import type * as dataParts from "../dataParts.js";
import type * as dataPartsPricing from "../dataPartsPricing.js";
import type * as dataPassports from "../dataPassports.js";
import type * as dataPricingEngine from "../dataPricingEngine.js";
import type * as dataProvenance from "../dataProvenance.js";
import type * as dataPublic from "../dataPublic.js";
import type * as dataServiceCatalog from "../dataServiceCatalog.js";
import type * as dataSources from "../dataSources.js";
import type * as dataTires from "../dataTires.js";
import type * as dataVehicleResolve from "../dataVehicleResolve.js";
import type * as dataVerification from "../dataVerification.js";
import type * as dataVins from "../dataVins.js";
import type * as devOnly_ageOilRecord from "../devOnly/ageOilRecord.js";
import type * as devOnly_auditConfigs from "../devOnly/auditConfigs.js";
import type * as devOnly_auditCoreRoles from "../devOnly/auditCoreRoles.js";
import type * as devOnly_auditPartRejections from "../devOnly/auditPartRejections.js";
import type * as devOnly_auditRunFlow from "../devOnly/auditRunFlow.js";
import type * as devOnly_backfillBrakeSystem from "../devOnly/backfillBrakeSystem.js";
import type * as devOnly_backfillSettlement from "../devOnly/backfillSettlement.js";
import type * as devOnly_batchAfter from "../devOnly/batchAfter.js";
import type * as devOnly_batchCandidates from "../devOnly/batchCandidates.js";
import type * as devOnly_batchSources from "../devOnly/batchSources.js";
import type * as devOnly_canaryRun from "../devOnly/canaryRun.js";
import type * as devOnly_claimCensus from "../devOnly/claimCensus.js";
import type * as devOnly_dataFixes from "../devOnly/dataFixes.js";
import type * as devOnly_dedupeConfig from "../devOnly/dedupeConfig.js";
import type * as devOnly_deployProbe from "../devOnly/deployProbe.js";
import type * as devOnly_endpointBackfill from "../devOnly/endpointBackfill.js";
import type * as devOnly_endpointPartPriceBackfill from "../devOnly/endpointPartPriceBackfill.js";
import type * as devOnly_endpointResearch from "../devOnly/endpointResearch.js";
import type * as devOnly_estimatorMinutesSpread from "../devOnly/estimatorMinutesSpread.js";
import type * as devOnly_evalJudge from "../devOnly/evalJudge.js";
import type * as devOnly_fallbackVsOlp from "../devOnly/fallbackVsOlp.js";
import type * as devOnly_findVehicleOwnerByVinTail from "../devOnly/findVehicleOwnerByVinTail.js";
import type * as devOnly_fluidPackAudit from "../devOnly/fluidPackAudit.js";
import type * as devOnly_fuelCensus from "../devOnly/fuelCensus.js";
import type * as devOnly_gateResweep from "../devOnly/gateResweep.js";
import type * as devOnly_importPorscheBundle from "../devOnly/importPorscheBundle.js";
import type * as devOnly_laborValidation from "../devOnly/laborValidation.js";
import type * as devOnly_laborWebSpread from "../devOnly/laborWebSpread.js";
import type * as devOnly_makeCoverageAudit from "../devOnly/makeCoverageAudit.js";
import type * as devOnly_oilCoverage from "../devOnly/oilCoverage.js";
import type * as devOnly_olpProbe from "../devOnly/olpProbe.js";
import type * as devOnly_partResurrectSweep from "../devOnly/partResurrectSweep.js";
import type * as devOnly_partsCoverage from "../devOnly/partsCoverage.js";
import type * as devOnly_purgeEstimatorObs from "../devOnly/purgeEstimatorObs.js";
import type * as devOnly_reassignShopLogins from "../devOnly/reassignShopLogins.js";
import type * as devOnly_reductoUsage from "../devOnly/reductoUsage.js";
import type * as devOnly_repriceJsonProbe from "../devOnly/repriceJsonProbe.js";
import type * as devOnly_resetEvalFixture from "../devOnly/resetEvalFixture.js";
import type * as devOnly_rockautoCatalogProbe from "../devOnly/rockautoCatalogProbe.js";
import type * as devOnly_rockautoProbe from "../devOnly/rockautoProbe.js";
import type * as devOnly_rockautoRungByVin from "../devOnly/rockautoRungByVin.js";
import type * as devOnly_rockautoSpecProbe from "../devOnly/rockautoSpecProbe.js";
import type * as devOnly_rotorManualPeek from "../devOnly/rotorManualPeek.js";
import type * as devOnly_rotorManualProbe from "../devOnly/rotorManualProbe.js";
import type * as devOnly_round3IdentityProbe from "../devOnly/round3IdentityProbe.js";
import type * as devOnly_round3StoredCheck from "../devOnly/round3StoredCheck.js";
import type * as devOnly_scanMessageLeaks from "../devOnly/scanMessageLeaks.js";
import type * as devOnly_seedChelalaCopy from "../devOnly/seedChelalaCopy.js";
import type * as devOnly_seedTestShops from "../devOnly/seedTestShops.js";
import type * as devOnly_sparkPlugQtyBackfill from "../devOnly/sparkPlugQtyBackfill.js";
import type * as devOnly_storePlatformProbe from "../devOnly/storePlatformProbe.js";
import type * as devOnly_summitProbe from "../devOnly/summitProbe.js";
import type * as devOnly_trimGarageToOneCar from "../devOnly/trimGarageToOneCar.js";
import type * as devOnly_urlProbe from "../devOnly/urlProbe.js";
import type * as devOnly_validateQuoteEngine from "../devOnly/validateQuoteEngine.js";
import type * as devOnly_vdbProbe from "../devOnly/vdbProbe.js";
import type * as devOnly_verifyLabor from "../devOnly/verifyLabor.js";
import type * as devOnly_verifyParts from "../devOnly/verifyParts.js";
import type * as devPortal from "../devPortal.js";
import type * as devScratch from "../devScratch.js";
import type * as diagnoseVin from "../diagnoseVin.js";
import type * as director from "../director.js";
import type * as directorCars from "../directorCars.js";
import type * as directorConfigActions from "../directorConfigActions.js";
import type * as directorConfigBackfills from "../directorConfigBackfills.js";
import type * as directorCustomJobs from "../directorCustomJobs.js";
import type * as directorData from "../directorData.js";
import type * as directorEnrichment from "../directorEnrichment.js";
import type * as directorEstimator from "../directorEstimator.js";
import type * as directorGate from "../directorGate.js";
import type * as directorIntegrations from "../directorIntegrations.js";
import type * as directorOverview from "../directorOverview.js";
import type * as directorPartQuality from "../directorPartQuality.js";
import type * as directorPricing from "../directorPricing.js";
import type * as directorSettings from "../directorSettings.js";
import type * as directorShopActions from "../directorShopActions.js";
import type * as directorStripe from "../directorStripe.js";
import type * as directorStripeLive from "../directorStripeLive.js";
import type * as directorUserActions from "../directorUserActions.js";
import type * as directorVehicleActions from "../directorVehicleActions.js";
import type * as director_auth from "../director_auth.js";
import type * as director_mechanic_edits from "../director_mechanic_edits.js";
import type * as director_mechanic_verifications from "../director_mechanic_verifications.js";
import type * as director_notes from "../director_notes.js";
import type * as director_service_parts from "../director_service_parts.js";
import type * as email_dispatcher from "../email_dispatcher.js";
import type * as engines from "../engines.js";
import type * as entitySummaries from "../entitySummaries.js";
import type * as files from "../files.js";
import type * as fitments from "../fitments.js";
import type * as fluidCatalog from "../fluidCatalog.js";
import type * as follow_ups from "../follow_ups.js";
import type * as healthPoints from "../healthPoints.js";
import type * as healthScoreWeights from "../healthScoreWeights.js";
import type * as http from "../http.js";
import type * as inspectionHealthConfig from "../inspectionHealthConfig.js";
import type * as inspectionHealthDeferred from "../inspectionHealthDeferred.js";
import type * as inspections from "../inspections.js";
import type * as inspections_template from "../inspections/template.js";
import type * as inspections_node from "../inspections_node.js";
import type * as invitations from "../invitations.js";
import type * as invoices from "../invoices.js";
import type * as invoices_template from "../invoices/template.js";
import type * as invoices_node from "../invoices_node.js";
import type * as jobBlockers from "../jobBlockers.js";
import type * as jobRecommendations from "../jobRecommendations.js";
import type * as job_actuals from "../job_actuals.js";
import type * as laborTimes from "../laborTimes.js";
import type * as labor_quote_snapshots from "../labor_quote_snapshots.js";
import type * as landing from "../landing.js";
import type * as lib_appleMapsGeocode from "../lib/appleMapsGeocode.js";
import type * as lib_bookingEnrichment from "../lib/bookingEnrichment.js";
import type * as lib_booking_field_redaction from "../lib/booking_field_redaction.js";
import type * as lib_brakeScope from "../lib/brakeScope.js";
import type * as lib_cancellation_policy from "../lib/cancellation_policy.js";
import type * as lib_checkin_questions from "../lib/checkin_questions.js";
import type * as lib_classifier from "../lib/classifier.js";
import type * as lib_customServiceNames from "../lib/customServiceNames.js";
import type * as lib_dataLayers from "../lib/dataLayers.js";
import type * as lib_email_provider from "../lib/email_provider.js";
import type * as lib_estimatorApi from "../lib/estimatorApi.js";
import type * as lib_estimatorEstimates from "../lib/estimatorEstimates.js";
import type * as lib_fallbackSnapshots from "../lib/fallbackSnapshots.js";
import type * as lib_fluidPackSize from "../lib/fluidPackSize.js";
import type * as lib_fuzzyServiceName from "../lib/fuzzyServiceName.js";
import type * as lib_haloVariantInference from "../lib/haloVariantInference.js";
import type * as lib_haloVariantRules from "../lib/haloVariantRules.js";
import type * as lib_hydrateInspectionState from "../lib/hydrateInspectionState.js";
import type * as lib_inspectionHealth from "../lib/inspectionHealth.js";
import type * as lib_intervals from "../lib/intervals.js";
import type * as lib_job_actuals from "../lib/job_actuals.js";
import type * as lib_laborBands from "../lib/laborBands.js";
import type * as lib_laborConstants from "../lib/laborConstants.js";
import type * as lib_laborFallback from "../lib/laborFallback.js";
import type * as lib_labor_aggregation from "../lib/labor_aggregation.js";
import type * as lib_late_start from "../lib/late_start.js";
import type * as lib_makeIdentity from "../lib/makeIdentity.js";
import type * as lib_makeKey from "../lib/makeKey.js";
import type * as lib_mechanic_verification_logging from "../lib/mechanic_verification_logging.js";
import type * as lib_mechanic_verifications from "../lib/mechanic_verifications.js";
import type * as lib_modifiers from "../lib/modifiers.js";
import type * as lib_money from "../lib/money.js";
import type * as lib_notificationScope from "../lib/notificationScope.js";
import type * as lib_otoActivity from "../lib/otoActivity.js";
import type * as lib_packageRules from "../lib/packageRules.js";
import type * as lib_partRoleQuantity from "../lib/partRoleQuantity.js";
import type * as lib_partSubcategories from "../lib/partSubcategories.js";
import type * as lib_partsBand from "../lib/partsBand.js";
import type * as lib_payment_constants from "../lib/payment_constants.js";
import type * as lib_priceBands from "../lib/priceBands.js";
import type * as lib_priceTypes from "../lib/priceTypes.js";
import type * as lib_publicLabor from "../lib/publicLabor.js";
import type * as lib_push_dispatcher from "../lib/push_dispatcher.js";
import type * as lib_quoteEngine from "../lib/quoteEngine.js";
import type * as lib_reviewFieldMap from "../lib/reviewFieldMap.js";
import type * as lib_robustStats from "../lib/robustStats.js";
import type * as lib_schedule_overlap from "../lib/schedule_overlap.js";
import type * as lib_serviceMatch from "../lib/serviceMatch.js";
import type * as lib_servicePartsReference from "../lib/servicePartsReference.js";
import type * as lib_serviceRecordType from "../lib/serviceRecordType.js";
import type * as lib_serviceSymptoms from "../lib/serviceSymptoms.js";
import type * as lib_serviceUnits from "../lib/serviceUnits.js";
import type * as lib_serviceWindow from "../lib/serviceWindow.js";
import type * as lib_shopAuth from "../lib/shopAuth.js";
import type * as lib_simpleTireScraper from "../lib/simpleTireScraper.js";
import type * as lib_sms_provider from "../lib/sms_provider.js";
import type * as lib_sourceNames from "../lib/sourceNames.js";
import type * as lib_sparkPlugs from "../lib/sparkPlugs.js";
import type * as lib_stripeTax from "../lib/stripeTax.js";
import type * as lib_stripe_void from "../lib/stripe_void.js";
import type * as lib_telnyx_webhook from "../lib/telnyx_webhook.js";
import type * as lib_timeSlotAvailability from "../lib/timeSlotAvailability.js";
import type * as lib_tireBrands from "../lib/tireBrands.js";
import type * as lib_tireRackScraper from "../lib/tireRackScraper.js";
import type * as lib_transmissionTypeInference from "../lib/transmissionTypeInference.js";
import type * as lib_vdbCache from "../lib/vdbCache.js";
import type * as lib_vehicleDatabases from "../lib/vehicleDatabases.js";
import type * as lib_vehicleTiers from "../lib/vehicleTiers.js";
import type * as lib_vehicle_image from "../lib/vehicle_image.js";
import type * as lib_vehicle_passports from "../lib/vehicle_passports.js";
import type * as lib_vinIdentity from "../lib/vinIdentity.js";
import type * as lib_walmartTireScraper from "../lib/walmartTireScraper.js";
import type * as maintenance from "../maintenance.js";
import type * as maintenance_pipeline from "../maintenance_pipeline.js";
import type * as makes from "../makes.js";
import type * as makesMerge from "../makesMerge.js";
import type * as manual_review_queue from "../manual_review_queue.js";
import type * as mcp_api from "../mcp_api.js";
import type * as mechanicNotifications from "../mechanicNotifications.js";
import type * as mechanics from "../mechanics.js";
import type * as migrations from "../migrations.js";
import type * as migrations_categoryConsolidation from "../migrations/categoryConsolidation.js";
import type * as migrations_directorRoles from "../migrations/directorRoles.js";
import type * as migrations_dropPrePurchaseInspection from "../migrations/dropPrePurchaseInspection.js";
import type * as migrations_purgeVendorNames from "../migrations/purgeVendorNames.js";
import type * as migrations_seedDataIncidents from "../migrations/seedDataIncidents.js";
import type * as models from "../models.js";
import type * as notificationPreferences from "../notificationPreferences.js";
import type * as notifications from "../notifications.js";
import type * as notifications_backfill from "../notifications_backfill.js";
import type * as oemParts from "../oemParts.js";
import type * as onboarding_questions_answers from "../onboarding_questions_answers.js";
import type * as opsAnalytics from "../opsAnalytics.js";
import type * as opsBookings from "../opsBookings.js";
import type * as opsDeletion from "../opsDeletion.js";
import type * as opsFollowUps from "../opsFollowUps.js";
import type * as opsOtoAi from "../opsOtoAi.js";
import type * as opsOverview from "../opsOverview.js";
import type * as opsPayments from "../opsPayments.js";
import type * as opsReviews from "../opsReviews.js";
import type * as opsSystemHealth from "../opsSystemHealth.js";
import type * as opsTransactions from "../opsTransactions.js";
import type * as opsUsers from "../opsUsers.js";
import type * as orphanRepair from "../orphanRepair.js";
import type * as oto_applicableServices from "../oto/applicableServices.js";
import type * as oto_bookings from "../oto/bookings.js";
import type * as oto_canonicalize from "../oto/canonicalize.js";
import type * as oto_chat from "../oto/chat.js";
import type * as oto_directorConversations from "../oto/directorConversations.js";
import type * as oto_dispatcher from "../oto/dispatcher.js";
import type * as oto_dueServices from "../oto/dueServices.js";
import type * as oto_envelope from "../oto/envelope.js";
import type * as oto_evalHarness from "../oto/evalHarness.js";
import type * as oto_evalTestFilter from "../oto/evalTestFilter.js";
import type * as oto_factAcquisition from "../oto/factAcquisition.js";
import type * as oto_factReports from "../oto/factReports.js";
import type * as oto_lookupVehicleSpec from "../oto/lookupVehicleSpec.js";
import type * as oto_memoryDecay from "../oto/memoryDecay.js";
import type * as oto_memoryEditing from "../oto/memoryEditing.js";
import type * as oto_memoryEquivalence from "../oto/memoryEquivalence.js";
import type * as oto_migrations_backfillV3Lifecycle from "../oto/migrations/backfillV3Lifecycle.js";
import type * as oto_migrations_evalTenantsSeed from "../oto/migrations/evalTenantsSeed.js";
import type * as oto_migrations_vehicleFactsReconciliation from "../oto/migrations/vehicleFactsReconciliation.js";
import type * as oto_migrations_verifiedFactsSeed from "../oto/migrations/verifiedFactsSeed.js";
import type * as oto_migrations_wave3Backfill from "../oto/migrations/wave3Backfill.js";
import type * as oto_moodMap from "../oto/moodMap.js";
import type * as oto_prompt_index from "../oto/prompt/index.js";
import type * as oto_prompt_stable from "../oto/prompt/stable.js";
import type * as oto_prompt_volatile from "../oto/prompt/volatile.js";
import type * as oto_promptChangelog from "../oto/promptChangelog.js";
import type * as oto_queryMoat from "../oto/queryMoat.js";
import type * as oto_recordConfirmation from "../oto/recordConfirmation.js";
import type * as oto_reliability from "../oto/reliability.js";
import type * as oto_resolveVehicle from "../oto/resolveVehicle.js";
import type * as oto_safety from "../oto/safety.js";
import type * as oto_searchedFacts from "../oto/searchedFacts.js";
import type * as oto_simulate from "../oto/simulate.js";
import type * as oto_system_prompt from "../oto/system_prompt.js";
import type * as oto_telemetry from "../oto/telemetry.js";
import type * as oto_telemetryAssembly from "../oto/telemetryAssembly.js";
import type * as oto_tools from "../oto/tools.js";
import type * as oto_vehicleFacts from "../oto/vehicleFacts.js";
import type * as oto_vehicleFactsEditing from "../oto/vehicleFactsEditing.js";
import type * as oto_vehicleFactsKB from "../oto/vehicleFactsKB.js";
import type * as oto_vehicleHealth from "../oto/vehicleHealth.js";
import type * as oto_vehicleTruthGuard from "../oto/vehicleTruthGuard.js";
import type * as partSelector from "../partSelector.js";
import type * as part_prices from "../part_prices.js";
import type * as part_snapshots from "../part_snapshots.js";
import type * as payment_disputes from "../payment_disputes.js";
import type * as payment_status_history from "../payment_status_history.js";
import type * as payments from "../payments.js";
import type * as payments_backfill from "../payments_backfill.js";
import type * as payments_backfill_created_at from "../payments_backfill_created_at.js";
import type * as payments_backfill_helpers from "../payments_backfill_helpers.js";
import type * as payments_reconcile from "../payments_reconcile.js";
import type * as payments_stripe from "../payments_stripe.js";
import type * as platform_settings from "../platform_settings.js";
import type * as portalSearch from "../portalSearch.js";
import type * as portalSeries from "../portalSeries.js";
import type * as portalStats from "../portalStats.js";
import type * as preSignups from "../preSignups.js";
import type * as preferences from "../preferences.js";
import type * as pricing from "../pricing.js";
import type * as quote_request_dismissals from "../quote_request_dismissals.js";
import type * as quotes from "../quotes.js";
import type * as referrals from "../referrals.js";
import type * as retrigger_enrichment from "../retrigger_enrichment.js";
import type * as reviewQueue from "../reviewQueue.js";
import type * as reviews from "../reviews.js";
import type * as rewards from "../rewards.js";
import type * as rotor_quote_responses from "../rotor_quote_responses.js";
import type * as schedule from "../schedule.js";
import type * as seed from "../seed.js";
import type * as seed_inspection_health from "../seed_inspection_health.js";
import type * as seed_modifier_weights from "../seed_modifier_weights.js";
import type * as seed_services from "../seed_services.js";
import type * as seed_services_catalog from "../seed_services_catalog.js";
import type * as seed_transactions from "../seed_transactions.js";
import type * as seeds_blockEbay from "../seeds/blockEbay.js";
import type * as seeds_cleanAndRerun from "../seeds/cleanAndRerun.js";
import type * as seeds_deleteAndRerunNissan from "../seeds/deleteAndRerunNissan.js";
import type * as seeds_deleteByVin from "../seeds/deleteByVin.js";
import type * as seeds_evidenceReport from "../seeds/evidenceReport.js";
import type * as seeds_fullCleanAndRerun from "../seeds/fullCleanAndRerun.js";
import type * as seeds_patchServiceOptions from "../seeds/patchServiceOptions.js";
import type * as seeds_seedBlockedDomains from "../seeds/seedBlockedDomains.js";
import type * as seeds_seedCamryBaseline from "../seeds/seedCamryBaseline.js";
import type * as seeds_seedMakes from "../seeds/seedMakes.js";
import type * as seeds_seedOilGrades from "../seeds/seedOilGrades.js";
import type * as seeds_seedPricing from "../seeds/seedPricing.js";
import type * as seeds_seedPricingV2 from "../seeds/seedPricingV2.js";
import type * as seeds_seedServiceCategories from "../seeds/seedServiceCategories.js";
import type * as seeds_seedServiceParts from "../seeds/seedServiceParts.js";
import type * as seeds_seedServicePartsRules from "../seeds/seedServicePartsRules.js";
import type * as seeds_seedServices from "../seeds/seedServices.js";
import type * as seeds_seedShopLaborRates from "../seeds/seedShopLaborRates.js";
import type * as seeds_seedTierAssignments from "../seeds/seedTierAssignments.js";
import type * as seeds_seedUniversalConsumables from "../seeds/seedUniversalConsumables.js";
import type * as seeds_setupPricingV2 from "../seeds/setupPricingV2.js";
import type * as seeds_testEnrichment from "../seeds/testEnrichment.js";
import type * as seeds_wipeServices from "../seeds/wipeServices.js";
import type * as seeds_wireUpChelala from "../seeds/wireUpChelala.js";
import type * as serviceMatch from "../serviceMatch.js";
import type * as serviceParts from "../serviceParts.js";
import type * as service_categories from "../service_categories.js";
import type * as service_insights from "../service_insights.js";
import type * as service_intervals_queries from "../service_intervals_queries.js";
import type * as service_options from "../service_options.js";
import type * as service_vehicle_specs from "../service_vehicle_specs.js";
import type * as services from "../services.js";
import type * as services_applicability from "../services/applicability.js";
import type * as services_consensus from "../services/consensus.js";
import type * as services_constants from "../services/constants.js";
import type * as services_laborDeterminant from "../services/laborDeterminant.js";
import type * as services_normalization from "../services/normalization.js";
import type * as services_sourceScoring from "../services/sourceScoring.js";
import type * as services_verification from "../services/verification.js";
import type * as shopApplications from "../shopApplications.js";
import type * as shopCustomServices from "../shopCustomServices.js";
import type * as shopCustomers from "../shopCustomers.js";
import type * as shopDisputes from "../shopDisputes.js";
import type * as shopInvites from "../shopInvites.js";
import type * as shopInvoices from "../shopInvoices.js";
import type * as shopLaborRates from "../shopLaborRates.js";
import type * as shopLicenses from "../shopLicenses.js";
import type * as shopPaymentRefunds from "../shopPaymentRefunds.js";
import type * as shopPayments from "../shopPayments.js";
import type * as shopServiceFixedPrices from "../shopServiceFixedPrices.js";
import type * as shop_part_preferences from "../shop_part_preferences.js";
import type * as shop_portfolio from "../shop_portfolio.js";
import type * as shop_services from "../shop_services.js";
import type * as shops from "../shops.js";
import type * as shopsCapacity from "../shopsCapacity.js";
import type * as shopsDirectory from "../shopsDirectory.js";
import type * as shopsGeo from "../shopsGeo.js";
import type * as shopsMechanics from "../shopsMechanics.js";
import type * as shopsNetwork from "../shopsNetwork.js";
import type * as shopsOfferings from "../shopsOfferings.js";
import type * as shopsPerformance from "../shopsPerformance.js";
import type * as shopsPipeline from "../shopsPipeline.js";
import type * as shopsReviews from "../shopsReviews.js";
import type * as shopsStripeHealth from "../shopsStripeHealth.js";
import type * as shops_hours from "../shops_hours.js";
import type * as slotHolds from "../slotHolds.js";
import type * as smartcar from "../smartcar.js";
import type * as sms_dispatcher from "../sms_dispatcher.js";
import type * as snapshotRevalidation from "../snapshotRevalidation.js";
import type * as spec_confirmations from "../spec_confirmations.js";
import type * as spec_variances from "../spec_variances.js";
import type * as specs from "../specs.js";
import type * as stripe_webhook_events from "../stripe_webhook_events.js";
import type * as support_requests_node from "../support_requests_node.js";
import type * as telnyx from "../telnyx.js";
import type * as test_helpers from "../test_helpers.js";
import type * as time_slots from "../time_slots.js";
import type * as tireBrands from "../tireBrands.js";
import type * as tireOptionsLookup from "../tireOptionsLookup.js";
import type * as tire_quote_responses from "../tire_quote_responses.js";
import type * as tires from "../tires.js";
import type * as tires_catalog from "../tires_catalog.js";
import type * as transactions from "../transactions.js";
import type * as transmissions from "../transmissions.js";
import type * as trims from "../trims.js";
import type * as two_factor from "../two_factor.js";
import type * as two_factor_node from "../two_factor_node.js";
import type * as undoMechanicVerification from "../undoMechanicVerification.js";
import type * as urgency from "../urgency.js";
import type * as userAddresses from "../userAddresses.js";
import type * as users from "../users.js";
import type * as vehicleDocuments from "../vehicleDocuments.js";
import type * as vehicleDocuments_node from "../vehicleDocuments_node.js";
import type * as vehicleEnrichment_adversarialVerification from "../vehicleEnrichment/adversarialVerification.js";
import type * as vehicleEnrichment_agentResearch from "../vehicleEnrichment/agentResearch.js";
import type * as vehicleEnrichment_anomalyDetection from "../vehicleEnrichment/anomalyDetection.js";
import type * as vehicleEnrichment_applicabilityRules from "../vehicleEnrichment/applicabilityRules.js";
import type * as vehicleEnrichment_backfillNhtsaKey from "../vehicleEnrichment/backfillNhtsaKey.js";
import type * as vehicleEnrichment_backfills from "../vehicleEnrichment/backfills.js";
import type * as vehicleEnrichment_blockedDomains from "../vehicleEnrichment/blockedDomains.js";
import type * as vehicleEnrichment_buildSourceResolver from "../vehicleEnrichment/buildSourceResolver.js";
import type * as vehicleEnrichment_cacheValidation from "../vehicleEnrichment/cacheValidation.js";
import type * as vehicleEnrichment_capacityResolver from "../vehicleEnrichment/capacityResolver.js";
import type * as vehicleEnrichment_categoryHarvest from "../vehicleEnrichment/categoryHarvest.js";
import type * as vehicleEnrichment_claimGathering from "../vehicleEnrichment/claimGathering.js";
import type * as vehicleEnrichment_completionGate from "../vehicleEnrichment/completionGate.js";
import type * as vehicleEnrichment_completionReevaluate from "../vehicleEnrichment/completionReevaluate.js";
import type * as vehicleEnrichment_contentSanitization from "../vehicleEnrichment/contentSanitization.js";
import type * as vehicleEnrichment_cylindersRepair from "../vehicleEnrichment/cylindersRepair.js";
import type * as vehicleEnrichment_determinismGate from "../vehicleEnrichment/determinismGate.js";
import type * as vehicleEnrichment_determinismProbe from "../vehicleEnrichment/determinismProbe.js";
import type * as vehicleEnrichment_drivetrainReconcile from "../vehicleEnrichment/drivetrainReconcile.js";
import type * as vehicleEnrichment_egressProxy from "../vehicleEnrichment/egressProxy.js";
import type * as vehicleEnrichment_endpointPartPriceMutations from "../vehicleEnrichment/endpointPartPriceMutations.js";
import type * as vehicleEnrichment_endpointPartPriceProjection from "../vehicleEnrichment/endpointPartPriceProjection.js";
import type * as vehicleEnrichment_epaFuelEconomy from "../vehicleEnrichment/epaFuelEconomy.js";
import type * as vehicleEnrichment_estimatorEndpoint from "../vehicleEnrichment/estimatorEndpoint.js";
import type * as vehicleEnrichment_estimatorEndpointMatch from "../vehicleEnrichment/estimatorEndpointMatch.js";
import type * as vehicleEnrichment_estimatorEndpointMutations from "../vehicleEnrichment/estimatorEndpointMutations.js";
import type * as vehicleEnrichment_estimatorEndpointProbe from "../vehicleEnrichment/estimatorEndpointProbe.js";
import type * as vehicleEnrichment_estimatorEndpointSibling from "../vehicleEnrichment/estimatorEndpointSibling.js";
import type * as vehicleEnrichment_evidenceConsensus from "../vehicleEnrichment/evidenceConsensus.js";
import type * as vehicleEnrichment_evidenceLatestBackfill from "../vehicleEnrichment/evidenceLatestBackfill.js";
import type * as vehicleEnrichment_firecrawl from "../vehicleEnrichment/firecrawl.js";
import type * as vehicleEnrichment_fitmentQuarantine from "../vehicleEnrichment/fitmentQuarantine.js";
import type * as vehicleEnrichment_fitmentReverify from "../vehicleEnrichment/fitmentReverify.js";
import type * as vehicleEnrichment_fleetEval from "../vehicleEnrichment/fleetEval.js";
import type * as vehicleEnrichment_fluidBrandConsistency from "../vehicleEnrichment/fluidBrandConsistency.js";
import type * as vehicleEnrichment_fuelTypeResolver from "../vehicleEnrichment/fuelTypeResolver.js";
import type * as vehicleEnrichment_generationGate from "../vehicleEnrichment/generationGate.js";
import type * as vehicleEnrichment_genuineFluids from "../vehicleEnrichment/genuineFluids.js";
import type * as vehicleEnrichment_helpers from "../vehicleEnrichment/helpers.js";
import type * as vehicleEnrichment_identityResolution from "../vehicleEnrichment/identityResolution.js";
import type * as vehicleEnrichment_laborRelabor from "../vehicleEnrichment/laborRelabor.js";
import type * as vehicleEnrichment_laborResearch from "../vehicleEnrichment/laborResearch.js";
import type * as vehicleEnrichment_laborSibling from "../vehicleEnrichment/laborSibling.js";
import type * as vehicleEnrichment_laborWebSearch from "../vehicleEnrichment/laborWebSearch.js";
import type * as vehicleEnrichment_lemonLabor from "../vehicleEnrichment/lemonLabor.js";
import type * as vehicleEnrichment_lemonManuals from "../vehicleEnrichment/lemonManuals.js";
import type * as vehicleEnrichment_makeCoverage from "../vehicleEnrichment/makeCoverage.js";
import type * as vehicleEnrichment_manualDirectSources from "../vehicleEnrichment/manualDirectSources.js";
import type * as vehicleEnrichment_manualLibrary from "../vehicleEnrichment/manualLibrary.js";
import type * as vehicleEnrichment_manualPageIndex from "../vehicleEnrichment/manualPageIndex.js";
import type * as vehicleEnrichment_manualPageIndex_node from "../vehicleEnrichment/manualPageIndex_node.js";
import type * as vehicleEnrichment_manualReducto from "../vehicleEnrichment/manualReducto.js";
import type * as vehicleEnrichment_manualSpecs from "../vehicleEnrichment/manualSpecs.js";
import type * as vehicleEnrichment_marketplaceScraper from "../vehicleEnrichment/marketplaceScraper.js";
import type * as vehicleEnrichment_mutations from "../vehicleEnrichment/mutations.js";
import type * as vehicleEnrichment_nhtsa from "../vehicleEnrichment/nhtsa.js";
import type * as vehicleEnrichment_nhtsaOdi from "../vehicleEnrichment/nhtsaOdi.js";
import type * as vehicleEnrichment_oilCatalog from "../vehicleEnrichment/oilCatalog.js";
import type * as vehicleEnrichment_oilProduct from "../vehicleEnrichment/oilProduct.js";
import type * as vehicleEnrichment_olpLabor from "../vehicleEnrichment/olpLabor.js";
import type * as vehicleEnrichment_olpLaborScrape from "../vehicleEnrichment/olpLaborScrape.js";
import type * as vehicleEnrichment_olpRelabor from "../vehicleEnrichment/olpRelabor.js";
import type * as vehicleEnrichment_partIndex from "../vehicleEnrichment/partIndex.js";
import type * as vehicleEnrichment_partialEnrichment from "../vehicleEnrichment/partialEnrichment.js";
import type * as vehicleEnrichment_pipelineTest from "../vehicleEnrichment/pipelineTest.js";
import type * as vehicleEnrichment_priceDiscovery from "../vehicleEnrichment/priceDiscovery.js";
import type * as vehicleEnrichment_priceParser from "../vehicleEnrichment/priceParser.js";
import type * as vehicleEnrichment_pricePilot from "../vehicleEnrichment/pricePilot.js";
import type * as vehicleEnrichment_priceReextract from "../vehicleEnrichment/priceReextract.js";
import type * as vehicleEnrichment_priceRefresh from "../vehicleEnrichment/priceRefresh.js";
import type * as vehicleEnrichment_prompts_batch1Prompt from "../vehicleEnrichment/prompts/batch1Prompt.js";
import type * as vehicleEnrichment_prompts_batch1bPrompt from "../vehicleEnrichment/prompts/batch1bPrompt.js";
import type * as vehicleEnrichment_prompts_batch2Prompt from "../vehicleEnrichment/prompts/batch2Prompt.js";
import type * as vehicleEnrichment_prompts_gapFillPrompt from "../vehicleEnrichment/prompts/gapFillPrompt.js";
import type * as vehicleEnrichment_queries from "../vehicleEnrichment/queries.js";
import type * as vehicleEnrichment_quotability from "../vehicleEnrichment/quotability.js";
import type * as vehicleEnrichment_rejectionResurrect from "../vehicleEnrichment/rejectionResurrect.js";
import type * as vehicleEnrichment_resourceRoles from "../vehicleEnrichment/resourceRoles.js";
import type * as vehicleEnrichment_reverseFitment from "../vehicleEnrichment/reverseFitment.js";
import type * as vehicleEnrichment_roleIdentity from "../vehicleEnrichment/roleIdentity.js";
import type * as vehicleEnrichment_roleIdentityAudit from "../vehicleEnrichment/roleIdentityAudit.js";
import type * as vehicleEnrichment_rotorThickness from "../vehicleEnrichment/rotorThickness.js";
import type * as vehicleEnrichment_routeIngest from "../vehicleEnrichment/routeIngest.js";
import type * as vehicleEnrichment_routeSources_assemble from "../vehicleEnrichment/routeSources/assemble.js";
import type * as vehicleEnrichment_routeSources_cache from "../vehicleEnrichment/routeSources/cache.js";
import type * as vehicleEnrichment_routeSources_ingest from "../vehicleEnrichment/routeSources/ingest.js";
import type * as vehicleEnrichment_routeSources_intervals from "../vehicleEnrichment/routeSources/intervals.js";
import type * as vehicleEnrichment_routeSources_manifest from "../vehicleEnrichment/routeSources/manifest.js";
import type * as vehicleEnrichment_routeSources_provenance from "../vehicleEnrichment/routeSources/provenance.js";
import type * as vehicleEnrichment_routeSources_types from "../vehicleEnrichment/routeSources/types.js";
import type * as vehicleEnrichment_routeSources_walk from "../vehicleEnrichment/routeSources/walk.js";
import type * as vehicleEnrichment_rpCatalog from "../vehicleEnrichment/rpCatalog.js";
import type * as vehicleEnrichment_runFence from "../vehicleEnrichment/runFence.js";
import type * as vehicleEnrichment_runHeadless from "../vehicleEnrichment/runHeadless.js";
import type * as vehicleEnrichment_runPublic from "../vehicleEnrichment/runPublic.js";
import type * as vehicleEnrichment_runSteps from "../vehicleEnrichment/runSteps.js";
import type * as vehicleEnrichment_runTest from "../vehicleEnrichment/runTest.js";
import type * as vehicleEnrichment_scraper from "../vehicleEnrichment/scraper.js";
import type * as vehicleEnrichment_scraperQueries from "../vehicleEnrichment/scraperQueries.js";
import type * as vehicleEnrichment_scrapling from "../vehicleEnrichment/scrapling.js";
import type * as vehicleEnrichment_servicesSnapshotBackfill from "../vehicleEnrichment/servicesSnapshotBackfill.js";
import type * as vehicleEnrichment_sourceAdapters_amsoil from "../vehicleEnrichment/sourceAdapters/amsoil.js";
import type * as vehicleEnrichment_sourceAdapters_brembo from "../vehicleEnrichment/sourceAdapters/brembo.js";
import type * as vehicleEnrichment_sourceAdapters_claimLedger from "../vehicleEnrichment/sourceAdapters/claimLedger.js";
import type * as vehicleEnrichment_sourceAdapters_http from "../vehicleEnrichment/sourceAdapters/http.js";
import type * as vehicleEnrichment_sourceAdapters_myCarUserManual from "../vehicleEnrichment/sourceAdapters/myCarUserManual.js";
import type * as vehicleEnrichment_sourceAdapters_registry from "../vehicleEnrichment/sourceAdapters/registry.js";
import type * as vehicleEnrichment_sourceAdapters_rockauto from "../vehicleEnrichment/sourceAdapters/rockauto.js";
import type * as vehicleEnrichment_sourceAdapters_rockautoCatalog from "../vehicleEnrichment/sourceAdapters/rockautoCatalog.js";
import type * as vehicleEnrichment_sourceAdapters_routeIngestor from "../vehicleEnrichment/sourceAdapters/routeIngestor.js";
import type * as vehicleEnrichment_sourceAdapters_summitCentric from "../vehicleEnrichment/sourceAdapters/summitCentric.js";
import type * as vehicleEnrichment_sourceAdapters_sylvaniaBulbs from "../vehicleEnrichment/sourceAdapters/sylvaniaBulbs.js";
import type * as vehicleEnrichment_sourceAdapters_tricoWipers from "../vehicleEnrichment/sourceAdapters/tricoWipers.js";
import type * as vehicleEnrichment_sourceAdapters_types from "../vehicleEnrichment/sourceAdapters/types.js";
import type * as vehicleEnrichment_sourceAdapters_wixFilters from "../vehicleEnrichment/sourceAdapters/wixFilters.js";
import type * as vehicleEnrichment_sourceDiscovery from "../vehicleEnrichment/sourceDiscovery.js";
import type * as vehicleEnrichment_sourceRegistry from "../vehicleEnrichment/sourceRegistry.js";
import type * as vehicleEnrichment_tier2Enrichment from "../vehicleEnrichment/tier2Enrichment.js";
import type * as vehicleEnrichment_transFluidSpecReconcile from "../vehicleEnrichment/transFluidSpecReconcile.js";
import type * as vehicleEnrichment_transmissionTypeReconcile from "../vehicleEnrichment/transmissionTypeReconcile.js";
import type * as vehicleEnrichment_types from "../vehicleEnrichment/types.js";
import type * as vehicleEnrichment_utils_batchClient from "../vehicleEnrichment/utils/batchClient.js";
import type * as vehicleEnrichment_utils_batchSchemas from "../vehicleEnrichment/utils/batchSchemas.js";
import type * as vehicleEnrichment_utils_chassisLookup from "../vehicleEnrichment/utils/chassisLookup.js";
import type * as vehicleEnrichment_utils_claudeClient from "../vehicleEnrichment/utils/claudeClient.js";
import type * as vehicleEnrichment_utils_engineCodeLookup from "../vehicleEnrichment/utils/engineCodeLookup.js";
import type * as vehicleEnrichment_utils_engineLookup from "../vehicleEnrichment/utils/engineLookup.js";
import type * as vehicleEnrichment_utils_enrichmentFlags from "../vehicleEnrichment/utils/enrichmentFlags.js";
import type * as vehicleEnrichment_utils_lateSanityFlags from "../vehicleEnrichment/utils/lateSanityFlags.js";
import type * as vehicleEnrichment_utils_partFitmentVerifier from "../vehicleEnrichment/utils/partFitmentVerifier.js";
import type * as vehicleEnrichment_utils_refuteHarvest from "../vehicleEnrichment/utils/refuteHarvest.js";
import type * as vehicleEnrichment_utils_roleBackfill from "../vehicleEnrichment/utils/roleBackfill.js";
import type * as vehicleEnrichment_utils_roleResource from "../vehicleEnrichment/utils/roleResource.js";
import type * as vehicleEnrichment_utils_rotorSpecResource from "../vehicleEnrichment/utils/rotorSpecResource.js";
import type * as vehicleEnrichment_utils_transFluidVerifier from "../vehicleEnrichment/utils/transFluidVerifier.js";
import type * as vehicleEnrichment_utils_wheelSizeScraper from "../vehicleEnrichment/utils/wheelSizeScraper.js";
import type * as vehicleEnrichment_v3TestSuite from "../vehicleEnrichment/v3TestSuite.js";
import type * as vehicleEnrichment_v3mutations from "../vehicleEnrichment/v3mutations.js";
import type * as vehicleEnrichment_v3pipeline from "../vehicleEnrichment/v3pipeline.js";
import type * as vehicleEnrichment_v3queries from "../vehicleEnrichment/v3queries.js";
import type * as vehicleEnrichment_validation_oemValidation from "../vehicleEnrichment/validation/oemValidation.js";
import type * as vehicleEnrichment_validation_sanityChecks from "../vehicleEnrichment/validation/sanityChecks.js";
import type * as vehicleEnrichment_validation_sourceAuthority from "../vehicleEnrichment/validation/sourceAuthority.js";
import type * as vehicleEnrichment_variantDecodeReconcile from "../vehicleEnrichment/variantDecodeReconcile.js";
import type * as vehicleEnrichment_variantFingerprint from "../vehicleEnrichment/variantFingerprint.js";
import type * as vehicleEnrichment_ymmtIdentity from "../vehicleEnrichment/ymmtIdentity.js";
import type * as vehicleTruth from "../vehicleTruth.js";
import type * as vehicle_history from "../vehicle_history.js";
import type * as vehicle_mutations from "../vehicle_mutations.js";
import type * as vehicle_owners from "../vehicle_owners.js";
import type * as vehicle_pipeline from "../vehicle_pipeline.js";
import type * as vehicle_specs from "../vehicle_specs.js";
import type * as vehicles from "../vehicles.js";
import type * as vinQueueQueries from "../vinQueueQueries.js";
import type * as walkinVinRepair from "../walkinVinRepair.js";
import type * as walkin_claims from "../walkin_claims.js";
import type * as ymmtCatalog from "../ymmtCatalog.js";
import type * as ymmtPipeline from "../ymmtPipeline.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  _diagnostic_i1_i2: typeof _diagnostic_i1_i2;
  _seedDemo: typeof _seedDemo;
  adminCleanupMechanics: typeof adminCleanupMechanics;
  ai_conversations: typeof ai_conversations;
  ai_enrichment_logs: typeof ai_enrichment_logs;
  ai_feedback: typeof ai_feedback;
  ai_messages: typeof ai_messages;
  analytics_events: typeof analytics_events;
  app_feedback: typeof app_feedback;
  audit_log: typeof audit_log;
  backfillTires: typeof backfillTires;
  backfillVdbBrakes: typeof backfillVdbBrakes;
  booking_activity: typeof booking_activity;
  booking_approvals: typeof booking_approvals;
  booking_disputes: typeof booking_disputes;
  booking_quotes: typeof booking_quotes;
  booking_status_history: typeof booking_status_history;
  bookings: typeof bookings;
  bugs: typeof bugs;
  cdn_assets: typeof cdn_assets;
  chassis_variants: typeof chassis_variants;
  checkin: typeof checkin;
  cleanup: typeof cleanup;
  client_logs: typeof client_logs;
  configsMerge: typeof configsMerge;
  conversion_funnels: typeof conversion_funnels;
  crons: typeof crons;
  customJobs: typeof customJobs;
  dataApi: typeof dataApi;
  dataApiEnrich: typeof dataApiEnrich;
  dataCatalog: typeof dataCatalog;
  dataControlRoom: typeof dataControlRoom;
  dataCosts: typeof dataCosts;
  dataCoverage: typeof dataCoverage;
  dataInsights: typeof dataInsights;
  dataLabor: typeof dataLabor;
  dataOverview: typeof dataOverview;
  dataParts: typeof dataParts;
  dataPartsPricing: typeof dataPartsPricing;
  dataPassports: typeof dataPassports;
  dataPricingEngine: typeof dataPricingEngine;
  dataProvenance: typeof dataProvenance;
  dataPublic: typeof dataPublic;
  dataServiceCatalog: typeof dataServiceCatalog;
  dataSources: typeof dataSources;
  dataTires: typeof dataTires;
  dataVehicleResolve: typeof dataVehicleResolve;
  dataVerification: typeof dataVerification;
  dataVins: typeof dataVins;
  "devOnly/ageOilRecord": typeof devOnly_ageOilRecord;
  "devOnly/auditConfigs": typeof devOnly_auditConfigs;
  "devOnly/auditCoreRoles": typeof devOnly_auditCoreRoles;
  "devOnly/auditPartRejections": typeof devOnly_auditPartRejections;
  "devOnly/auditRunFlow": typeof devOnly_auditRunFlow;
  "devOnly/backfillBrakeSystem": typeof devOnly_backfillBrakeSystem;
  "devOnly/backfillSettlement": typeof devOnly_backfillSettlement;
  "devOnly/batchAfter": typeof devOnly_batchAfter;
  "devOnly/batchCandidates": typeof devOnly_batchCandidates;
  "devOnly/batchSources": typeof devOnly_batchSources;
  "devOnly/canaryRun": typeof devOnly_canaryRun;
  "devOnly/claimCensus": typeof devOnly_claimCensus;
  "devOnly/dataFixes": typeof devOnly_dataFixes;
  "devOnly/dedupeConfig": typeof devOnly_dedupeConfig;
  "devOnly/deployProbe": typeof devOnly_deployProbe;
  "devOnly/endpointBackfill": typeof devOnly_endpointBackfill;
  "devOnly/endpointPartPriceBackfill": typeof devOnly_endpointPartPriceBackfill;
  "devOnly/endpointResearch": typeof devOnly_endpointResearch;
  "devOnly/estimatorMinutesSpread": typeof devOnly_estimatorMinutesSpread;
  "devOnly/evalJudge": typeof devOnly_evalJudge;
  "devOnly/fallbackVsOlp": typeof devOnly_fallbackVsOlp;
  "devOnly/findVehicleOwnerByVinTail": typeof devOnly_findVehicleOwnerByVinTail;
  "devOnly/fluidPackAudit": typeof devOnly_fluidPackAudit;
  "devOnly/fuelCensus": typeof devOnly_fuelCensus;
  "devOnly/gateResweep": typeof devOnly_gateResweep;
  "devOnly/importPorscheBundle": typeof devOnly_importPorscheBundle;
  "devOnly/laborValidation": typeof devOnly_laborValidation;
  "devOnly/laborWebSpread": typeof devOnly_laborWebSpread;
  "devOnly/makeCoverageAudit": typeof devOnly_makeCoverageAudit;
  "devOnly/oilCoverage": typeof devOnly_oilCoverage;
  "devOnly/olpProbe": typeof devOnly_olpProbe;
  "devOnly/partResurrectSweep": typeof devOnly_partResurrectSweep;
  "devOnly/partsCoverage": typeof devOnly_partsCoverage;
  "devOnly/purgeEstimatorObs": typeof devOnly_purgeEstimatorObs;
  "devOnly/reassignShopLogins": typeof devOnly_reassignShopLogins;
  "devOnly/reductoUsage": typeof devOnly_reductoUsage;
  "devOnly/repriceJsonProbe": typeof devOnly_repriceJsonProbe;
  "devOnly/resetEvalFixture": typeof devOnly_resetEvalFixture;
  "devOnly/rockautoCatalogProbe": typeof devOnly_rockautoCatalogProbe;
  "devOnly/rockautoProbe": typeof devOnly_rockautoProbe;
  "devOnly/rockautoRungByVin": typeof devOnly_rockautoRungByVin;
  "devOnly/rockautoSpecProbe": typeof devOnly_rockautoSpecProbe;
  "devOnly/rotorManualPeek": typeof devOnly_rotorManualPeek;
  "devOnly/rotorManualProbe": typeof devOnly_rotorManualProbe;
  "devOnly/round3IdentityProbe": typeof devOnly_round3IdentityProbe;
  "devOnly/round3StoredCheck": typeof devOnly_round3StoredCheck;
  "devOnly/scanMessageLeaks": typeof devOnly_scanMessageLeaks;
  "devOnly/seedChelalaCopy": typeof devOnly_seedChelalaCopy;
  "devOnly/seedTestShops": typeof devOnly_seedTestShops;
  "devOnly/sparkPlugQtyBackfill": typeof devOnly_sparkPlugQtyBackfill;
  "devOnly/storePlatformProbe": typeof devOnly_storePlatformProbe;
  "devOnly/summitProbe": typeof devOnly_summitProbe;
  "devOnly/trimGarageToOneCar": typeof devOnly_trimGarageToOneCar;
  "devOnly/urlProbe": typeof devOnly_urlProbe;
  "devOnly/validateQuoteEngine": typeof devOnly_validateQuoteEngine;
  "devOnly/vdbProbe": typeof devOnly_vdbProbe;
  "devOnly/verifyLabor": typeof devOnly_verifyLabor;
  "devOnly/verifyParts": typeof devOnly_verifyParts;
  devPortal: typeof devPortal;
  devScratch: typeof devScratch;
  diagnoseVin: typeof diagnoseVin;
  director: typeof director;
  directorCars: typeof directorCars;
  directorConfigActions: typeof directorConfigActions;
  directorConfigBackfills: typeof directorConfigBackfills;
  directorCustomJobs: typeof directorCustomJobs;
  directorData: typeof directorData;
  directorEnrichment: typeof directorEnrichment;
  directorEstimator: typeof directorEstimator;
  directorGate: typeof directorGate;
  directorIntegrations: typeof directorIntegrations;
  directorOverview: typeof directorOverview;
  directorPartQuality: typeof directorPartQuality;
  directorPricing: typeof directorPricing;
  directorSettings: typeof directorSettings;
  directorShopActions: typeof directorShopActions;
  directorStripe: typeof directorStripe;
  directorStripeLive: typeof directorStripeLive;
  directorUserActions: typeof directorUserActions;
  directorVehicleActions: typeof directorVehicleActions;
  director_auth: typeof director_auth;
  director_mechanic_edits: typeof director_mechanic_edits;
  director_mechanic_verifications: typeof director_mechanic_verifications;
  director_notes: typeof director_notes;
  director_service_parts: typeof director_service_parts;
  email_dispatcher: typeof email_dispatcher;
  engines: typeof engines;
  entitySummaries: typeof entitySummaries;
  files: typeof files;
  fitments: typeof fitments;
  fluidCatalog: typeof fluidCatalog;
  follow_ups: typeof follow_ups;
  healthPoints: typeof healthPoints;
  healthScoreWeights: typeof healthScoreWeights;
  http: typeof http;
  inspectionHealthConfig: typeof inspectionHealthConfig;
  inspectionHealthDeferred: typeof inspectionHealthDeferred;
  inspections: typeof inspections;
  "inspections/template": typeof inspections_template;
  inspections_node: typeof inspections_node;
  invitations: typeof invitations;
  invoices: typeof invoices;
  "invoices/template": typeof invoices_template;
  invoices_node: typeof invoices_node;
  jobBlockers: typeof jobBlockers;
  jobRecommendations: typeof jobRecommendations;
  job_actuals: typeof job_actuals;
  laborTimes: typeof laborTimes;
  labor_quote_snapshots: typeof labor_quote_snapshots;
  landing: typeof landing;
  "lib/appleMapsGeocode": typeof lib_appleMapsGeocode;
  "lib/bookingEnrichment": typeof lib_bookingEnrichment;
  "lib/booking_field_redaction": typeof lib_booking_field_redaction;
  "lib/brakeScope": typeof lib_brakeScope;
  "lib/cancellation_policy": typeof lib_cancellation_policy;
  "lib/checkin_questions": typeof lib_checkin_questions;
  "lib/classifier": typeof lib_classifier;
  "lib/customServiceNames": typeof lib_customServiceNames;
  "lib/dataLayers": typeof lib_dataLayers;
  "lib/email_provider": typeof lib_email_provider;
  "lib/estimatorApi": typeof lib_estimatorApi;
  "lib/estimatorEstimates": typeof lib_estimatorEstimates;
  "lib/fallbackSnapshots": typeof lib_fallbackSnapshots;
  "lib/fluidPackSize": typeof lib_fluidPackSize;
  "lib/fuzzyServiceName": typeof lib_fuzzyServiceName;
  "lib/haloVariantInference": typeof lib_haloVariantInference;
  "lib/haloVariantRules": typeof lib_haloVariantRules;
  "lib/hydrateInspectionState": typeof lib_hydrateInspectionState;
  "lib/inspectionHealth": typeof lib_inspectionHealth;
  "lib/intervals": typeof lib_intervals;
  "lib/job_actuals": typeof lib_job_actuals;
  "lib/laborBands": typeof lib_laborBands;
  "lib/laborConstants": typeof lib_laborConstants;
  "lib/laborFallback": typeof lib_laborFallback;
  "lib/labor_aggregation": typeof lib_labor_aggregation;
  "lib/late_start": typeof lib_late_start;
  "lib/makeIdentity": typeof lib_makeIdentity;
  "lib/makeKey": typeof lib_makeKey;
  "lib/mechanic_verification_logging": typeof lib_mechanic_verification_logging;
  "lib/mechanic_verifications": typeof lib_mechanic_verifications;
  "lib/modifiers": typeof lib_modifiers;
  "lib/money": typeof lib_money;
  "lib/notificationScope": typeof lib_notificationScope;
  "lib/otoActivity": typeof lib_otoActivity;
  "lib/packageRules": typeof lib_packageRules;
  "lib/partRoleQuantity": typeof lib_partRoleQuantity;
  "lib/partSubcategories": typeof lib_partSubcategories;
  "lib/partsBand": typeof lib_partsBand;
  "lib/payment_constants": typeof lib_payment_constants;
  "lib/priceBands": typeof lib_priceBands;
  "lib/priceTypes": typeof lib_priceTypes;
  "lib/publicLabor": typeof lib_publicLabor;
  "lib/push_dispatcher": typeof lib_push_dispatcher;
  "lib/quoteEngine": typeof lib_quoteEngine;
  "lib/reviewFieldMap": typeof lib_reviewFieldMap;
  "lib/robustStats": typeof lib_robustStats;
  "lib/schedule_overlap": typeof lib_schedule_overlap;
  "lib/serviceMatch": typeof lib_serviceMatch;
  "lib/servicePartsReference": typeof lib_servicePartsReference;
  "lib/serviceRecordType": typeof lib_serviceRecordType;
  "lib/serviceSymptoms": typeof lib_serviceSymptoms;
  "lib/serviceUnits": typeof lib_serviceUnits;
  "lib/serviceWindow": typeof lib_serviceWindow;
  "lib/shopAuth": typeof lib_shopAuth;
  "lib/simpleTireScraper": typeof lib_simpleTireScraper;
  "lib/sms_provider": typeof lib_sms_provider;
  "lib/sourceNames": typeof lib_sourceNames;
  "lib/sparkPlugs": typeof lib_sparkPlugs;
  "lib/stripeTax": typeof lib_stripeTax;
  "lib/stripe_void": typeof lib_stripe_void;
  "lib/telnyx_webhook": typeof lib_telnyx_webhook;
  "lib/timeSlotAvailability": typeof lib_timeSlotAvailability;
  "lib/tireBrands": typeof lib_tireBrands;
  "lib/tireRackScraper": typeof lib_tireRackScraper;
  "lib/transmissionTypeInference": typeof lib_transmissionTypeInference;
  "lib/vdbCache": typeof lib_vdbCache;
  "lib/vehicleDatabases": typeof lib_vehicleDatabases;
  "lib/vehicleTiers": typeof lib_vehicleTiers;
  "lib/vehicle_image": typeof lib_vehicle_image;
  "lib/vehicle_passports": typeof lib_vehicle_passports;
  "lib/vinIdentity": typeof lib_vinIdentity;
  "lib/walmartTireScraper": typeof lib_walmartTireScraper;
  maintenance: typeof maintenance;
  maintenance_pipeline: typeof maintenance_pipeline;
  makes: typeof makes;
  makesMerge: typeof makesMerge;
  manual_review_queue: typeof manual_review_queue;
  mcp_api: typeof mcp_api;
  mechanicNotifications: typeof mechanicNotifications;
  mechanics: typeof mechanics;
  migrations: typeof migrations;
  "migrations/categoryConsolidation": typeof migrations_categoryConsolidation;
  "migrations/directorRoles": typeof migrations_directorRoles;
  "migrations/dropPrePurchaseInspection": typeof migrations_dropPrePurchaseInspection;
  "migrations/purgeVendorNames": typeof migrations_purgeVendorNames;
  "migrations/seedDataIncidents": typeof migrations_seedDataIncidents;
  models: typeof models;
  notificationPreferences: typeof notificationPreferences;
  notifications: typeof notifications;
  notifications_backfill: typeof notifications_backfill;
  oemParts: typeof oemParts;
  onboarding_questions_answers: typeof onboarding_questions_answers;
  opsAnalytics: typeof opsAnalytics;
  opsBookings: typeof opsBookings;
  opsDeletion: typeof opsDeletion;
  opsFollowUps: typeof opsFollowUps;
  opsOtoAi: typeof opsOtoAi;
  opsOverview: typeof opsOverview;
  opsPayments: typeof opsPayments;
  opsReviews: typeof opsReviews;
  opsSystemHealth: typeof opsSystemHealth;
  opsTransactions: typeof opsTransactions;
  opsUsers: typeof opsUsers;
  orphanRepair: typeof orphanRepair;
  "oto/applicableServices": typeof oto_applicableServices;
  "oto/bookings": typeof oto_bookings;
  "oto/canonicalize": typeof oto_canonicalize;
  "oto/chat": typeof oto_chat;
  "oto/directorConversations": typeof oto_directorConversations;
  "oto/dispatcher": typeof oto_dispatcher;
  "oto/dueServices": typeof oto_dueServices;
  "oto/envelope": typeof oto_envelope;
  "oto/evalHarness": typeof oto_evalHarness;
  "oto/evalTestFilter": typeof oto_evalTestFilter;
  "oto/factAcquisition": typeof oto_factAcquisition;
  "oto/factReports": typeof oto_factReports;
  "oto/lookupVehicleSpec": typeof oto_lookupVehicleSpec;
  "oto/memoryDecay": typeof oto_memoryDecay;
  "oto/memoryEditing": typeof oto_memoryEditing;
  "oto/memoryEquivalence": typeof oto_memoryEquivalence;
  "oto/migrations/backfillV3Lifecycle": typeof oto_migrations_backfillV3Lifecycle;
  "oto/migrations/evalTenantsSeed": typeof oto_migrations_evalTenantsSeed;
  "oto/migrations/vehicleFactsReconciliation": typeof oto_migrations_vehicleFactsReconciliation;
  "oto/migrations/verifiedFactsSeed": typeof oto_migrations_verifiedFactsSeed;
  "oto/migrations/wave3Backfill": typeof oto_migrations_wave3Backfill;
  "oto/moodMap": typeof oto_moodMap;
  "oto/prompt/index": typeof oto_prompt_index;
  "oto/prompt/stable": typeof oto_prompt_stable;
  "oto/prompt/volatile": typeof oto_prompt_volatile;
  "oto/promptChangelog": typeof oto_promptChangelog;
  "oto/queryMoat": typeof oto_queryMoat;
  "oto/recordConfirmation": typeof oto_recordConfirmation;
  "oto/reliability": typeof oto_reliability;
  "oto/resolveVehicle": typeof oto_resolveVehicle;
  "oto/safety": typeof oto_safety;
  "oto/searchedFacts": typeof oto_searchedFacts;
  "oto/simulate": typeof oto_simulate;
  "oto/system_prompt": typeof oto_system_prompt;
  "oto/telemetry": typeof oto_telemetry;
  "oto/telemetryAssembly": typeof oto_telemetryAssembly;
  "oto/tools": typeof oto_tools;
  "oto/vehicleFacts": typeof oto_vehicleFacts;
  "oto/vehicleFactsEditing": typeof oto_vehicleFactsEditing;
  "oto/vehicleFactsKB": typeof oto_vehicleFactsKB;
  "oto/vehicleHealth": typeof oto_vehicleHealth;
  "oto/vehicleTruthGuard": typeof oto_vehicleTruthGuard;
  partSelector: typeof partSelector;
  part_prices: typeof part_prices;
  part_snapshots: typeof part_snapshots;
  payment_disputes: typeof payment_disputes;
  payment_status_history: typeof payment_status_history;
  payments: typeof payments;
  payments_backfill: typeof payments_backfill;
  payments_backfill_created_at: typeof payments_backfill_created_at;
  payments_backfill_helpers: typeof payments_backfill_helpers;
  payments_reconcile: typeof payments_reconcile;
  payments_stripe: typeof payments_stripe;
  platform_settings: typeof platform_settings;
  portalSearch: typeof portalSearch;
  portalSeries: typeof portalSeries;
  portalStats: typeof portalStats;
  preSignups: typeof preSignups;
  preferences: typeof preferences;
  pricing: typeof pricing;
  quote_request_dismissals: typeof quote_request_dismissals;
  quotes: typeof quotes;
  referrals: typeof referrals;
  retrigger_enrichment: typeof retrigger_enrichment;
  reviewQueue: typeof reviewQueue;
  reviews: typeof reviews;
  rewards: typeof rewards;
  rotor_quote_responses: typeof rotor_quote_responses;
  schedule: typeof schedule;
  seed: typeof seed;
  seed_inspection_health: typeof seed_inspection_health;
  seed_modifier_weights: typeof seed_modifier_weights;
  seed_services: typeof seed_services;
  seed_services_catalog: typeof seed_services_catalog;
  seed_transactions: typeof seed_transactions;
  "seeds/blockEbay": typeof seeds_blockEbay;
  "seeds/cleanAndRerun": typeof seeds_cleanAndRerun;
  "seeds/deleteAndRerunNissan": typeof seeds_deleteAndRerunNissan;
  "seeds/deleteByVin": typeof seeds_deleteByVin;
  "seeds/evidenceReport": typeof seeds_evidenceReport;
  "seeds/fullCleanAndRerun": typeof seeds_fullCleanAndRerun;
  "seeds/patchServiceOptions": typeof seeds_patchServiceOptions;
  "seeds/seedBlockedDomains": typeof seeds_seedBlockedDomains;
  "seeds/seedCamryBaseline": typeof seeds_seedCamryBaseline;
  "seeds/seedMakes": typeof seeds_seedMakes;
  "seeds/seedOilGrades": typeof seeds_seedOilGrades;
  "seeds/seedPricing": typeof seeds_seedPricing;
  "seeds/seedPricingV2": typeof seeds_seedPricingV2;
  "seeds/seedServiceCategories": typeof seeds_seedServiceCategories;
  "seeds/seedServiceParts": typeof seeds_seedServiceParts;
  "seeds/seedServicePartsRules": typeof seeds_seedServicePartsRules;
  "seeds/seedServices": typeof seeds_seedServices;
  "seeds/seedShopLaborRates": typeof seeds_seedShopLaborRates;
  "seeds/seedTierAssignments": typeof seeds_seedTierAssignments;
  "seeds/seedUniversalConsumables": typeof seeds_seedUniversalConsumables;
  "seeds/setupPricingV2": typeof seeds_setupPricingV2;
  "seeds/testEnrichment": typeof seeds_testEnrichment;
  "seeds/wipeServices": typeof seeds_wipeServices;
  "seeds/wireUpChelala": typeof seeds_wireUpChelala;
  serviceMatch: typeof serviceMatch;
  serviceParts: typeof serviceParts;
  service_categories: typeof service_categories;
  service_insights: typeof service_insights;
  service_intervals_queries: typeof service_intervals_queries;
  service_options: typeof service_options;
  service_vehicle_specs: typeof service_vehicle_specs;
  services: typeof services;
  "services/applicability": typeof services_applicability;
  "services/consensus": typeof services_consensus;
  "services/constants": typeof services_constants;
  "services/laborDeterminant": typeof services_laborDeterminant;
  "services/normalization": typeof services_normalization;
  "services/sourceScoring": typeof services_sourceScoring;
  "services/verification": typeof services_verification;
  shopApplications: typeof shopApplications;
  shopCustomServices: typeof shopCustomServices;
  shopCustomers: typeof shopCustomers;
  shopDisputes: typeof shopDisputes;
  shopInvites: typeof shopInvites;
  shopInvoices: typeof shopInvoices;
  shopLaborRates: typeof shopLaborRates;
  shopLicenses: typeof shopLicenses;
  shopPaymentRefunds: typeof shopPaymentRefunds;
  shopPayments: typeof shopPayments;
  shopServiceFixedPrices: typeof shopServiceFixedPrices;
  shop_part_preferences: typeof shop_part_preferences;
  shop_portfolio: typeof shop_portfolio;
  shop_services: typeof shop_services;
  shops: typeof shops;
  shopsCapacity: typeof shopsCapacity;
  shopsDirectory: typeof shopsDirectory;
  shopsGeo: typeof shopsGeo;
  shopsMechanics: typeof shopsMechanics;
  shopsNetwork: typeof shopsNetwork;
  shopsOfferings: typeof shopsOfferings;
  shopsPerformance: typeof shopsPerformance;
  shopsPipeline: typeof shopsPipeline;
  shopsReviews: typeof shopsReviews;
  shopsStripeHealth: typeof shopsStripeHealth;
  shops_hours: typeof shops_hours;
  slotHolds: typeof slotHolds;
  smartcar: typeof smartcar;
  sms_dispatcher: typeof sms_dispatcher;
  snapshotRevalidation: typeof snapshotRevalidation;
  spec_confirmations: typeof spec_confirmations;
  spec_variances: typeof spec_variances;
  specs: typeof specs;
  stripe_webhook_events: typeof stripe_webhook_events;
  support_requests_node: typeof support_requests_node;
  telnyx: typeof telnyx;
  test_helpers: typeof test_helpers;
  time_slots: typeof time_slots;
  tireBrands: typeof tireBrands;
  tireOptionsLookup: typeof tireOptionsLookup;
  tire_quote_responses: typeof tire_quote_responses;
  tires: typeof tires;
  tires_catalog: typeof tires_catalog;
  transactions: typeof transactions;
  transmissions: typeof transmissions;
  trims: typeof trims;
  two_factor: typeof two_factor;
  two_factor_node: typeof two_factor_node;
  undoMechanicVerification: typeof undoMechanicVerification;
  urgency: typeof urgency;
  userAddresses: typeof userAddresses;
  users: typeof users;
  vehicleDocuments: typeof vehicleDocuments;
  vehicleDocuments_node: typeof vehicleDocuments_node;
  "vehicleEnrichment/adversarialVerification": typeof vehicleEnrichment_adversarialVerification;
  "vehicleEnrichment/agentResearch": typeof vehicleEnrichment_agentResearch;
  "vehicleEnrichment/anomalyDetection": typeof vehicleEnrichment_anomalyDetection;
  "vehicleEnrichment/applicabilityRules": typeof vehicleEnrichment_applicabilityRules;
  "vehicleEnrichment/backfillNhtsaKey": typeof vehicleEnrichment_backfillNhtsaKey;
  "vehicleEnrichment/backfills": typeof vehicleEnrichment_backfills;
  "vehicleEnrichment/blockedDomains": typeof vehicleEnrichment_blockedDomains;
  "vehicleEnrichment/buildSourceResolver": typeof vehicleEnrichment_buildSourceResolver;
  "vehicleEnrichment/cacheValidation": typeof vehicleEnrichment_cacheValidation;
  "vehicleEnrichment/capacityResolver": typeof vehicleEnrichment_capacityResolver;
  "vehicleEnrichment/categoryHarvest": typeof vehicleEnrichment_categoryHarvest;
  "vehicleEnrichment/claimGathering": typeof vehicleEnrichment_claimGathering;
  "vehicleEnrichment/completionGate": typeof vehicleEnrichment_completionGate;
  "vehicleEnrichment/completionReevaluate": typeof vehicleEnrichment_completionReevaluate;
  "vehicleEnrichment/contentSanitization": typeof vehicleEnrichment_contentSanitization;
  "vehicleEnrichment/cylindersRepair": typeof vehicleEnrichment_cylindersRepair;
  "vehicleEnrichment/determinismGate": typeof vehicleEnrichment_determinismGate;
  "vehicleEnrichment/determinismProbe": typeof vehicleEnrichment_determinismProbe;
  "vehicleEnrichment/drivetrainReconcile": typeof vehicleEnrichment_drivetrainReconcile;
  "vehicleEnrichment/egressProxy": typeof vehicleEnrichment_egressProxy;
  "vehicleEnrichment/endpointPartPriceMutations": typeof vehicleEnrichment_endpointPartPriceMutations;
  "vehicleEnrichment/endpointPartPriceProjection": typeof vehicleEnrichment_endpointPartPriceProjection;
  "vehicleEnrichment/epaFuelEconomy": typeof vehicleEnrichment_epaFuelEconomy;
  "vehicleEnrichment/estimatorEndpoint": typeof vehicleEnrichment_estimatorEndpoint;
  "vehicleEnrichment/estimatorEndpointMatch": typeof vehicleEnrichment_estimatorEndpointMatch;
  "vehicleEnrichment/estimatorEndpointMutations": typeof vehicleEnrichment_estimatorEndpointMutations;
  "vehicleEnrichment/estimatorEndpointProbe": typeof vehicleEnrichment_estimatorEndpointProbe;
  "vehicleEnrichment/estimatorEndpointSibling": typeof vehicleEnrichment_estimatorEndpointSibling;
  "vehicleEnrichment/evidenceConsensus": typeof vehicleEnrichment_evidenceConsensus;
  "vehicleEnrichment/evidenceLatestBackfill": typeof vehicleEnrichment_evidenceLatestBackfill;
  "vehicleEnrichment/firecrawl": typeof vehicleEnrichment_firecrawl;
  "vehicleEnrichment/fitmentQuarantine": typeof vehicleEnrichment_fitmentQuarantine;
  "vehicleEnrichment/fitmentReverify": typeof vehicleEnrichment_fitmentReverify;
  "vehicleEnrichment/fleetEval": typeof vehicleEnrichment_fleetEval;
  "vehicleEnrichment/fluidBrandConsistency": typeof vehicleEnrichment_fluidBrandConsistency;
  "vehicleEnrichment/fuelTypeResolver": typeof vehicleEnrichment_fuelTypeResolver;
  "vehicleEnrichment/generationGate": typeof vehicleEnrichment_generationGate;
  "vehicleEnrichment/genuineFluids": typeof vehicleEnrichment_genuineFluids;
  "vehicleEnrichment/helpers": typeof vehicleEnrichment_helpers;
  "vehicleEnrichment/identityResolution": typeof vehicleEnrichment_identityResolution;
  "vehicleEnrichment/laborRelabor": typeof vehicleEnrichment_laborRelabor;
  "vehicleEnrichment/laborResearch": typeof vehicleEnrichment_laborResearch;
  "vehicleEnrichment/laborSibling": typeof vehicleEnrichment_laborSibling;
  "vehicleEnrichment/laborWebSearch": typeof vehicleEnrichment_laborWebSearch;
  "vehicleEnrichment/lemonLabor": typeof vehicleEnrichment_lemonLabor;
  "vehicleEnrichment/lemonManuals": typeof vehicleEnrichment_lemonManuals;
  "vehicleEnrichment/makeCoverage": typeof vehicleEnrichment_makeCoverage;
  "vehicleEnrichment/manualDirectSources": typeof vehicleEnrichment_manualDirectSources;
  "vehicleEnrichment/manualLibrary": typeof vehicleEnrichment_manualLibrary;
  "vehicleEnrichment/manualPageIndex": typeof vehicleEnrichment_manualPageIndex;
  "vehicleEnrichment/manualPageIndex_node": typeof vehicleEnrichment_manualPageIndex_node;
  "vehicleEnrichment/manualReducto": typeof vehicleEnrichment_manualReducto;
  "vehicleEnrichment/manualSpecs": typeof vehicleEnrichment_manualSpecs;
  "vehicleEnrichment/marketplaceScraper": typeof vehicleEnrichment_marketplaceScraper;
  "vehicleEnrichment/mutations": typeof vehicleEnrichment_mutations;
  "vehicleEnrichment/nhtsa": typeof vehicleEnrichment_nhtsa;
  "vehicleEnrichment/nhtsaOdi": typeof vehicleEnrichment_nhtsaOdi;
  "vehicleEnrichment/oilCatalog": typeof vehicleEnrichment_oilCatalog;
  "vehicleEnrichment/oilProduct": typeof vehicleEnrichment_oilProduct;
  "vehicleEnrichment/olpLabor": typeof vehicleEnrichment_olpLabor;
  "vehicleEnrichment/olpLaborScrape": typeof vehicleEnrichment_olpLaborScrape;
  "vehicleEnrichment/olpRelabor": typeof vehicleEnrichment_olpRelabor;
  "vehicleEnrichment/partIndex": typeof vehicleEnrichment_partIndex;
  "vehicleEnrichment/partialEnrichment": typeof vehicleEnrichment_partialEnrichment;
  "vehicleEnrichment/pipelineTest": typeof vehicleEnrichment_pipelineTest;
  "vehicleEnrichment/priceDiscovery": typeof vehicleEnrichment_priceDiscovery;
  "vehicleEnrichment/priceParser": typeof vehicleEnrichment_priceParser;
  "vehicleEnrichment/pricePilot": typeof vehicleEnrichment_pricePilot;
  "vehicleEnrichment/priceReextract": typeof vehicleEnrichment_priceReextract;
  "vehicleEnrichment/priceRefresh": typeof vehicleEnrichment_priceRefresh;
  "vehicleEnrichment/prompts/batch1Prompt": typeof vehicleEnrichment_prompts_batch1Prompt;
  "vehicleEnrichment/prompts/batch1bPrompt": typeof vehicleEnrichment_prompts_batch1bPrompt;
  "vehicleEnrichment/prompts/batch2Prompt": typeof vehicleEnrichment_prompts_batch2Prompt;
  "vehicleEnrichment/prompts/gapFillPrompt": typeof vehicleEnrichment_prompts_gapFillPrompt;
  "vehicleEnrichment/queries": typeof vehicleEnrichment_queries;
  "vehicleEnrichment/quotability": typeof vehicleEnrichment_quotability;
  "vehicleEnrichment/rejectionResurrect": typeof vehicleEnrichment_rejectionResurrect;
  "vehicleEnrichment/resourceRoles": typeof vehicleEnrichment_resourceRoles;
  "vehicleEnrichment/reverseFitment": typeof vehicleEnrichment_reverseFitment;
  "vehicleEnrichment/roleIdentity": typeof vehicleEnrichment_roleIdentity;
  "vehicleEnrichment/roleIdentityAudit": typeof vehicleEnrichment_roleIdentityAudit;
  "vehicleEnrichment/rotorThickness": typeof vehicleEnrichment_rotorThickness;
  "vehicleEnrichment/routeIngest": typeof vehicleEnrichment_routeIngest;
  "vehicleEnrichment/routeSources/assemble": typeof vehicleEnrichment_routeSources_assemble;
  "vehicleEnrichment/routeSources/cache": typeof vehicleEnrichment_routeSources_cache;
  "vehicleEnrichment/routeSources/ingest": typeof vehicleEnrichment_routeSources_ingest;
  "vehicleEnrichment/routeSources/intervals": typeof vehicleEnrichment_routeSources_intervals;
  "vehicleEnrichment/routeSources/manifest": typeof vehicleEnrichment_routeSources_manifest;
  "vehicleEnrichment/routeSources/provenance": typeof vehicleEnrichment_routeSources_provenance;
  "vehicleEnrichment/routeSources/types": typeof vehicleEnrichment_routeSources_types;
  "vehicleEnrichment/routeSources/walk": typeof vehicleEnrichment_routeSources_walk;
  "vehicleEnrichment/rpCatalog": typeof vehicleEnrichment_rpCatalog;
  "vehicleEnrichment/runFence": typeof vehicleEnrichment_runFence;
  "vehicleEnrichment/runHeadless": typeof vehicleEnrichment_runHeadless;
  "vehicleEnrichment/runPublic": typeof vehicleEnrichment_runPublic;
  "vehicleEnrichment/runSteps": typeof vehicleEnrichment_runSteps;
  "vehicleEnrichment/runTest": typeof vehicleEnrichment_runTest;
  "vehicleEnrichment/scraper": typeof vehicleEnrichment_scraper;
  "vehicleEnrichment/scraperQueries": typeof vehicleEnrichment_scraperQueries;
  "vehicleEnrichment/scrapling": typeof vehicleEnrichment_scrapling;
  "vehicleEnrichment/servicesSnapshotBackfill": typeof vehicleEnrichment_servicesSnapshotBackfill;
  "vehicleEnrichment/sourceAdapters/amsoil": typeof vehicleEnrichment_sourceAdapters_amsoil;
  "vehicleEnrichment/sourceAdapters/brembo": typeof vehicleEnrichment_sourceAdapters_brembo;
  "vehicleEnrichment/sourceAdapters/claimLedger": typeof vehicleEnrichment_sourceAdapters_claimLedger;
  "vehicleEnrichment/sourceAdapters/http": typeof vehicleEnrichment_sourceAdapters_http;
  "vehicleEnrichment/sourceAdapters/myCarUserManual": typeof vehicleEnrichment_sourceAdapters_myCarUserManual;
  "vehicleEnrichment/sourceAdapters/registry": typeof vehicleEnrichment_sourceAdapters_registry;
  "vehicleEnrichment/sourceAdapters/rockauto": typeof vehicleEnrichment_sourceAdapters_rockauto;
  "vehicleEnrichment/sourceAdapters/rockautoCatalog": typeof vehicleEnrichment_sourceAdapters_rockautoCatalog;
  "vehicleEnrichment/sourceAdapters/routeIngestor": typeof vehicleEnrichment_sourceAdapters_routeIngestor;
  "vehicleEnrichment/sourceAdapters/summitCentric": typeof vehicleEnrichment_sourceAdapters_summitCentric;
  "vehicleEnrichment/sourceAdapters/sylvaniaBulbs": typeof vehicleEnrichment_sourceAdapters_sylvaniaBulbs;
  "vehicleEnrichment/sourceAdapters/tricoWipers": typeof vehicleEnrichment_sourceAdapters_tricoWipers;
  "vehicleEnrichment/sourceAdapters/types": typeof vehicleEnrichment_sourceAdapters_types;
  "vehicleEnrichment/sourceAdapters/wixFilters": typeof vehicleEnrichment_sourceAdapters_wixFilters;
  "vehicleEnrichment/sourceDiscovery": typeof vehicleEnrichment_sourceDiscovery;
  "vehicleEnrichment/sourceRegistry": typeof vehicleEnrichment_sourceRegistry;
  "vehicleEnrichment/tier2Enrichment": typeof vehicleEnrichment_tier2Enrichment;
  "vehicleEnrichment/transFluidSpecReconcile": typeof vehicleEnrichment_transFluidSpecReconcile;
  "vehicleEnrichment/transmissionTypeReconcile": typeof vehicleEnrichment_transmissionTypeReconcile;
  "vehicleEnrichment/types": typeof vehicleEnrichment_types;
  "vehicleEnrichment/utils/batchClient": typeof vehicleEnrichment_utils_batchClient;
  "vehicleEnrichment/utils/batchSchemas": typeof vehicleEnrichment_utils_batchSchemas;
  "vehicleEnrichment/utils/chassisLookup": typeof vehicleEnrichment_utils_chassisLookup;
  "vehicleEnrichment/utils/claudeClient": typeof vehicleEnrichment_utils_claudeClient;
  "vehicleEnrichment/utils/engineCodeLookup": typeof vehicleEnrichment_utils_engineCodeLookup;
  "vehicleEnrichment/utils/engineLookup": typeof vehicleEnrichment_utils_engineLookup;
  "vehicleEnrichment/utils/enrichmentFlags": typeof vehicleEnrichment_utils_enrichmentFlags;
  "vehicleEnrichment/utils/lateSanityFlags": typeof vehicleEnrichment_utils_lateSanityFlags;
  "vehicleEnrichment/utils/partFitmentVerifier": typeof vehicleEnrichment_utils_partFitmentVerifier;
  "vehicleEnrichment/utils/refuteHarvest": typeof vehicleEnrichment_utils_refuteHarvest;
  "vehicleEnrichment/utils/roleBackfill": typeof vehicleEnrichment_utils_roleBackfill;
  "vehicleEnrichment/utils/roleResource": typeof vehicleEnrichment_utils_roleResource;
  "vehicleEnrichment/utils/rotorSpecResource": typeof vehicleEnrichment_utils_rotorSpecResource;
  "vehicleEnrichment/utils/transFluidVerifier": typeof vehicleEnrichment_utils_transFluidVerifier;
  "vehicleEnrichment/utils/wheelSizeScraper": typeof vehicleEnrichment_utils_wheelSizeScraper;
  "vehicleEnrichment/v3TestSuite": typeof vehicleEnrichment_v3TestSuite;
  "vehicleEnrichment/v3mutations": typeof vehicleEnrichment_v3mutations;
  "vehicleEnrichment/v3pipeline": typeof vehicleEnrichment_v3pipeline;
  "vehicleEnrichment/v3queries": typeof vehicleEnrichment_v3queries;
  "vehicleEnrichment/validation/oemValidation": typeof vehicleEnrichment_validation_oemValidation;
  "vehicleEnrichment/validation/sanityChecks": typeof vehicleEnrichment_validation_sanityChecks;
  "vehicleEnrichment/validation/sourceAuthority": typeof vehicleEnrichment_validation_sourceAuthority;
  "vehicleEnrichment/variantDecodeReconcile": typeof vehicleEnrichment_variantDecodeReconcile;
  "vehicleEnrichment/variantFingerprint": typeof vehicleEnrichment_variantFingerprint;
  "vehicleEnrichment/ymmtIdentity": typeof vehicleEnrichment_ymmtIdentity;
  vehicleTruth: typeof vehicleTruth;
  vehicle_history: typeof vehicle_history;
  vehicle_mutations: typeof vehicle_mutations;
  vehicle_owners: typeof vehicle_owners;
  vehicle_pipeline: typeof vehicle_pipeline;
  vehicle_specs: typeof vehicle_specs;
  vehicles: typeof vehicles;
  vinQueueQueries: typeof vinQueueQueries;
  walkinVinRepair: typeof walkinVinRepair;
  walkin_claims: typeof walkin_claims;
  ymmtCatalog: typeof ymmtCatalog;
  ymmtPipeline: typeof ymmtPipeline;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
