import { internalMutation } from "../_generated/server";
import { Id } from "../_generated/dataModel";

/**
 * Seeds the service_categories and services tables with all 23 v3 services.
 * Safe to re-run: skips if services table already has data.
 *
 * Run via: npx convex run seeds/seedServices:seedServices
 */
export const seedServices = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if services already seeded
    const existing = await ctx.db.query("services").first();
    if (existing) {
      console.log("Services table already has data — skipping seed.");
      return;
    }

    // ── Step 1: Seed service categories ──
    const categoryData = [
      { name: "Diagnostics", icon_name: "scan-search", display_order: 1 },
      { name: "Compliance", icon_name: "shield-check", display_order: 2 },
      { name: "Routine Maintenance", icon_name: "wrench", display_order: 3 },
      { name: "Tires", icon_name: "circle-dot", display_order: 4 },
      { name: "Brakes", icon_name: "disc", display_order: 5 },
      { name: "Battery", icon_name: "battery-charging", display_order: 6 },
      { name: "Fluids", icon_name: "droplets", display_order: 7 },
    ] as const;

    const categories: Record<string, Id<"service_categories">> = {};
    for (const cat of categoryData) {
      const id = await ctx.db.insert("service_categories", cat);
      categories[cat.name] = id;
    }

    // ── Step 2: Seed all 23 services ──
    const services = [
      // Diagnostics (1-3)
      {
        name: "Diagnostic Scan",
        slug: "diagnostic_scan",
        description: "OBD-II scan to read and clear diagnostic trouble codes",
        display_order: 1,
        service_category_id: categories["Diagnostics"],
        default_labor_hours: 0.5,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
        min_model_year: 1996,
      },
      {
        name: "Pre-Purchase Inspection",
        slug: "pre_purchase_inspection",
        description: "Comprehensive multi-point inspection before buying a used vehicle",
        display_order: 2,
        service_category_id: categories["Diagnostics"],
        default_labor_hours: 1.75,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Check Engine Light Diagnosis",
        slug: "check_engine_light",
        description: "Diagnose check engine light with code reading and root cause analysis",
        display_order: 3,
        service_category_id: categories["Diagnostics"],
        default_labor_hours: 1.0,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
        min_model_year: 1996,
      },

      // Compliance (4-5)
      {
        name: "State Inspection",
        slug: "state_inspection",
        description: "Annual state safety inspection certification",
        display_order: 4,
        service_category_id: categories["Compliance"],
        default_labor_hours: 0.5,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: true,
        requires_emissions_test: false,
      },
      {
        name: "Emissions Test",
        slug: "emissions_test",
        description: "State-required emissions compliance test",
        display_order: 5,
        service_category_id: categories["Compliance"],
        default_labor_hours: 0.3,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: true,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: true,
      },

      // Routine Maintenance (6-11)
      {
        name: "Oil Change",
        slug: "oil_change",
        description: "Engine oil and filter replacement with OEM-spec oil",
        display_order: 6,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 0.4,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: true,
        requires_ice_engine: true,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Filter Replacement",
        slug: "filter_replacement",
        description: "Engine air filter and cabin air filter replacement",
        display_order: 7,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 0.35,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Spark Plugs",
        slug: "spark_plugs",
        description: "Spark plug replacement with OEM-spec plugs",
        display_order: 8,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 1.5,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: true,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Timing Belt",
        slug: "timing_belt",
        description: "Timing belt kit replacement including tensioner and idler pulleys",
        display_order: 9,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 5.0,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: true,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Coolant Flush",
        slug: "coolant_flush",
        description: "Full cooling system flush and refill with OEM coolant",
        display_order: 10,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 1.25,
        is_labor_only: false,
        has_options: false,
        requires_parts: false,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Transmission Service",
        slug: "transmission_service",
        description: "Transmission fluid drain-and-fill with OEM-spec fluid",
        display_order: 11,
        service_category_id: categories["Routine Maintenance"],
        default_labor_hours: 1.5,
        is_labor_only: false,
        has_options: false,
        requires_parts: false,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },

      // Tires (12-15)
      {
        name: "Tire Rotation",
        slug: "tire_rotation",
        description: "Rotate tires to promote even wear and extend tire life",
        display_order: 12,
        service_category_id: categories["Tires"],
        default_labor_hours: 0.4,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: true,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Tire Balance",
        slug: "tire_balance",
        description: "Balance all four wheels to eliminate vibration",
        display_order: 13,
        service_category_id: categories["Tires"],
        default_labor_hours: 0.75,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Wheel Alignment",
        slug: "wheel_alignment",
        description: "Adjust wheel angles to manufacturer specifications",
        display_order: 14,
        service_category_id: categories["Tires"],
        default_labor_hours: 1.0,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Tire Replacement",
        slug: "tire_replacement",
        description: "Mount and balance new tires to OEM size specifications",
        display_order: 15,
        service_category_id: categories["Tires"],
        default_labor_hours: 1.25,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },

      // Brakes (16-18)
      {
        name: "Brake Pad Replacement",
        slug: "brake_pad_replacement",
        description: "Replace front and/or rear brake pads with OEM parts",
        display_order: 16,
        service_category_id: categories["Brakes"],
        default_labor_hours: 1.5,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Rotor Replacement",
        slug: "rotor_replacement",
        description: "Replace brake rotors and pads for front and/or rear axle",
        display_order: 17,
        service_category_id: categories["Brakes"],
        default_labor_hours: 3.0,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Brake Fluid Flush",
        slug: "brake_fluid_flush",
        description: "Full brake fluid flush and bleed at all four corners",
        display_order: 18,
        service_category_id: categories["Brakes"],
        default_labor_hours: 0.85,
        is_labor_only: false,
        has_options: false,
        requires_parts: false,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },

      // Battery (19-20)
      {
        name: "Battery Test",
        slug: "battery_test",
        description: "Load test battery and charging system health check",
        display_order: 19,
        service_category_id: categories["Battery"],
        default_labor_hours: 0.2,
        is_labor_only: true,
        has_options: false,
        requires_parts: false,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Battery Replacement",
        slug: "battery_replacement",
        description: "Replace battery with correct group size and CCA rating",
        display_order: 20,
        service_category_id: categories["Battery"],
        default_labor_hours: 0.5,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },

      // Fluids (21-23)
      {
        name: "Power Steering Flush",
        slug: "power_steering_flush",
        description: "Flush and replace power steering fluid",
        display_order: 21,
        service_category_id: categories["Fluids"],
        default_labor_hours: 0.75,
        is_labor_only: false,
        has_options: false,
        requires_parts: false,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: true,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Differential Service",
        slug: "differential_service",
        description: "Drain and refill differential and transfer case fluid",
        display_order: 22,
        service_category_id: categories["Fluids"],
        default_labor_hours: 1.0,
        is_labor_only: false,
        has_options: false,
        requires_parts: false,
        requires_fluids: true,
        requires_ice_engine: false,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: true,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
      {
        name: "Fuel System Cleaning",
        slug: "fuel_system_cleaning",
        description: "Clean fuel injectors and intake valves to restore performance",
        display_order: 23,
        service_category_id: categories["Fluids"],
        default_labor_hours: 1.0,
        is_labor_only: false,
        has_options: false,
        requires_parts: true,
        requires_fluids: false,
        requires_ice_engine: true,
        requires_timing_belt: false,
        requires_hydraulic_ps: false,
        requires_differential: false,
        requires_rotatable_tires: false,
        requires_state_inspection: false,
        requires_emissions_test: false,
      },
    ];

    // Insert all services
    for (const service of services) {
      await ctx.db.insert("services", service);
    }

    console.log(
      `Seeded ${categoryData.length} service categories and ${services.length} services.`
    );
  },
});
