// Maps 2-letter US state/territory codes to their primary IANA timezone.
// For states that span multiple zones, the most populous zone is used as the
// auto-detected default — the shop owner can override in Settings.
export const US_STATE_TIMEZONE: Record<string, string> = {
  AL: "America/Chicago",
  AK: "America/Anchorage",
  AZ: "America/Phoenix",
  AR: "America/Chicago",
  CA: "America/Los_Angeles",
  CO: "America/Denver",
  CT: "America/New_York",
  DE: "America/New_York",
  FL: "America/New_York",
  GA: "America/New_York",
  HI: "Pacific/Honolulu",
  ID: "America/Denver",
  IL: "America/Chicago",
  IN: "America/Indiana/Indianapolis",
  IA: "America/Chicago",
  KS: "America/Chicago",
  KY: "America/New_York",
  LA: "America/Chicago",
  ME: "America/New_York",
  MD: "America/New_York",
  MA: "America/New_York",
  MI: "America/Detroit",
  MN: "America/Chicago",
  MS: "America/Chicago",
  MO: "America/Chicago",
  MT: "America/Denver",
  NE: "America/Chicago",
  NV: "America/Los_Angeles",
  NH: "America/New_York",
  NJ: "America/New_York",
  NM: "America/Denver",
  NY: "America/New_York",
  NC: "America/New_York",
  ND: "America/Chicago",
  OH: "America/New_York",
  OK: "America/Chicago",
  OR: "America/Los_Angeles",
  PA: "America/New_York",
  RI: "America/New_York",
  SC: "America/New_York",
  SD: "America/Chicago",
  TN: "America/Chicago",
  TX: "America/Chicago",
  UT: "America/Denver",
  VT: "America/New_York",
  VA: "America/New_York",
  WA: "America/Los_Angeles",
  WV: "America/New_York",
  WI: "America/Chicago",
  WY: "America/Denver",
  DC: "America/New_York",
  PR: "America/Puerto_Rico",
  VI: "America/St_Thomas",
  GU: "Pacific/Guam",
  AS: "Pacific/Pago_Pago",
  MP: "Pacific/Saipan",
};

export const US_TIMEZONES: Array<{ value: string; label: string }> = [
  { value: "America/New_York",            label: "Eastern (ET) — New York, Miami, Atlanta" },
  { value: "America/Chicago",             label: "Central (CT) — Chicago, Dallas, Houston" },
  { value: "America/Denver",              label: "Mountain (MT) — Denver, Salt Lake City" },
  { value: "America/Phoenix",             label: "Mountain no DST — Phoenix, Tucson" },
  { value: "America/Los_Angeles",         label: "Pacific (PT) — Los Angeles, Seattle" },
  { value: "America/Anchorage",           label: "Alaska (AKT) — Anchorage" },
  { value: "Pacific/Honolulu",            label: "Hawaii (HT) — Honolulu" },
  { value: "America/Puerto_Rico",         label: "Atlantic (AT) — Puerto Rico, Virgin Islands" },
  { value: "America/Indiana/Indianapolis", label: "Indiana (ET, no DST) — Indianapolis" },
  { value: "America/Detroit",             label: "Michigan (ET) — Detroit" },
];

/** Returns the IANA timezone for a 2-letter US state code, or null if unknown. */
export function detectTimezoneFromState(state: string | null | undefined): string | null {
  if (!state) return null;
  return US_STATE_TIMEZONE[state.trim().toUpperCase()] ?? null;
}
